// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dota_gcmessages_client_chat.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CMsgGCToClientPrivateChatResponse_Result int32

const (
	CMsgGCToClientPrivateChatResponse_SUCCESS                       CMsgGCToClientPrivateChatResponse_Result = 0
	CMsgGCToClientPrivateChatResponse_FAILURE_CREATION_LOCK         CMsgGCToClientPrivateChatResponse_Result = 1
	CMsgGCToClientPrivateChatResponse_FAILURE_SQL_TRANSACTION       CMsgGCToClientPrivateChatResponse_Result = 2
	CMsgGCToClientPrivateChatResponse_FAILURE_SDO_LOAD              CMsgGCToClientPrivateChatResponse_Result = 3
	CMsgGCToClientPrivateChatResponse_FAILURE_NO_PERMISSION         CMsgGCToClientPrivateChatResponse_Result = 4
	CMsgGCToClientPrivateChatResponse_FAILURE_ALREADY_MEMBER        CMsgGCToClientPrivateChatResponse_Result = 5
	CMsgGCToClientPrivateChatResponse_FAILURE_NOT_A_MEMBER          CMsgGCToClientPrivateChatResponse_Result = 7
	CMsgGCToClientPrivateChatResponse_FAILURE_NO_REMAINING_ADMINS   CMsgGCToClientPrivateChatResponse_Result = 8
	CMsgGCToClientPrivateChatResponse_FAILURE_NO_ROOM               CMsgGCToClientPrivateChatResponse_Result = 9
	CMsgGCToClientPrivateChatResponse_FAILURE_CREATION_RATE_LIMITED CMsgGCToClientPrivateChatResponse_Result = 10
	CMsgGCToClientPrivateChatResponse_FAILURE_UNKNOWN_CHANNEL_NAME  CMsgGCToClientPrivateChatResponse_Result = 11
	CMsgGCToClientPrivateChatResponse_FAILURE_UNKNOWN_USER          CMsgGCToClientPrivateChatResponse_Result = 12
	CMsgGCToClientPrivateChatResponse_FAILURE_UNKNOWN_ERROR         CMsgGCToClientPrivateChatResponse_Result = 13
	CMsgGCToClientPrivateChatResponse_FAILURE_CANNOT_KICK_ADMIN     CMsgGCToClientPrivateChatResponse_Result = 14
	CMsgGCToClientPrivateChatResponse_FAILURE_ALREADY_ADMIN         CMsgGCToClientPrivateChatResponse_Result = 15
)

var CMsgGCToClientPrivateChatResponse_Result_name = map[int32]string{
	0:  "SUCCESS",
	1:  "FAILURE_CREATION_LOCK",
	2:  "FAILURE_SQL_TRANSACTION",
	3:  "FAILURE_SDO_LOAD",
	4:  "FAILURE_NO_PERMISSION",
	5:  "FAILURE_ALREADY_MEMBER",
	7:  "FAILURE_NOT_A_MEMBER",
	8:  "FAILURE_NO_REMAINING_ADMINS",
	9:  "FAILURE_NO_ROOM",
	10: "FAILURE_CREATION_RATE_LIMITED",
	11: "FAILURE_UNKNOWN_CHANNEL_NAME",
	12: "FAILURE_UNKNOWN_USER",
	13: "FAILURE_UNKNOWN_ERROR",
	14: "FAILURE_CANNOT_KICK_ADMIN",
	15: "FAILURE_ALREADY_ADMIN",
}

var CMsgGCToClientPrivateChatResponse_Result_value = map[string]int32{
	"SUCCESS":                       0,
	"FAILURE_CREATION_LOCK":         1,
	"FAILURE_SQL_TRANSACTION":       2,
	"FAILURE_SDO_LOAD":              3,
	"FAILURE_NO_PERMISSION":         4,
	"FAILURE_ALREADY_MEMBER":        5,
	"FAILURE_NOT_A_MEMBER":          7,
	"FAILURE_NO_REMAINING_ADMINS":   8,
	"FAILURE_NO_ROOM":               9,
	"FAILURE_CREATION_RATE_LIMITED": 10,
	"FAILURE_UNKNOWN_CHANNEL_NAME":  11,
	"FAILURE_UNKNOWN_USER":          12,
	"FAILURE_UNKNOWN_ERROR":         13,
	"FAILURE_CANNOT_KICK_ADMIN":     14,
	"FAILURE_ALREADY_ADMIN":         15,
}

func (x CMsgGCToClientPrivateChatResponse_Result) Enum() *CMsgGCToClientPrivateChatResponse_Result {
	p := new(CMsgGCToClientPrivateChatResponse_Result)
	*p = x
	return p
}

func (x CMsgGCToClientPrivateChatResponse_Result) String() string {
	return proto.EnumName(CMsgGCToClientPrivateChatResponse_Result_name, int32(x))
}

func (x *CMsgGCToClientPrivateChatResponse_Result) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgGCToClientPrivateChatResponse_Result_value, data, "CMsgGCToClientPrivateChatResponse_Result")
	if err != nil {
		return err
	}
	*x = CMsgGCToClientPrivateChatResponse_Result(value)
	return nil
}

func (CMsgGCToClientPrivateChatResponse_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{4, 0}
}

type CMsgDOTAJoinChatChannelResponse_Result int32

const (
	CMsgDOTAJoinChatChannelResponse_JOIN_SUCCESS                     CMsgDOTAJoinChatChannelResponse_Result = 0
	CMsgDOTAJoinChatChannelResponse_INVALID_CHANNEL_TYPE             CMsgDOTAJoinChatChannelResponse_Result = 1
	CMsgDOTAJoinChatChannelResponse_ACCOUNT_NOT_FOUND                CMsgDOTAJoinChatChannelResponse_Result = 2
	CMsgDOTAJoinChatChannelResponse_ACH_FAILED                       CMsgDOTAJoinChatChannelResponse_Result = 3
	CMsgDOTAJoinChatChannelResponse_USER_IN_TOO_MANY_CHANNELS        CMsgDOTAJoinChatChannelResponse_Result = 4
	CMsgDOTAJoinChatChannelResponse_RATE_LIMIT_EXCEEDED              CMsgDOTAJoinChatChannelResponse_Result = 5
	CMsgDOTAJoinChatChannelResponse_CHANNEL_FULL                     CMsgDOTAJoinChatChannelResponse_Result = 6
	CMsgDOTAJoinChatChannelResponse_CHANNEL_FULL_OVERFLOWED          CMsgDOTAJoinChatChannelResponse_Result = 7
	CMsgDOTAJoinChatChannelResponse_FAILED_TO_ADD_USER               CMsgDOTAJoinChatChannelResponse_Result = 8
	CMsgDOTAJoinChatChannelResponse_CHANNEL_TYPE_DISABLED            CMsgDOTAJoinChatChannelResponse_Result = 9
	CMsgDOTAJoinChatChannelResponse_PRIVATE_CHAT_CREATE_FAILED       CMsgDOTAJoinChatChannelResponse_Result = 10
	CMsgDOTAJoinChatChannelResponse_PRIVATE_CHAT_NO_PERMISSION       CMsgDOTAJoinChatChannelResponse_Result = 11
	CMsgDOTAJoinChatChannelResponse_PRIVATE_CHAT_CREATE_LOCK_FAILED  CMsgDOTAJoinChatChannelResponse_Result = 12
	CMsgDOTAJoinChatChannelResponse_PRIVATE_CHAT_KICKED              CMsgDOTAJoinChatChannelResponse_Result = 13
	CMsgDOTAJoinChatChannelResponse_USER_NOT_ALLOWED                 CMsgDOTAJoinChatChannelResponse_Result = 14
	CMsgDOTAJoinChatChannelResponse_ENSURE_SPECIAL_PRIVILEGES_FAILED CMsgDOTAJoinChatChannelResponse_Result = 15
	CMsgDOTAJoinChatChannelResponse_NEW_PLAYER_USER_NOT_ELIGIBLE     CMsgDOTAJoinChatChannelResponse_Result = 16
	CMsgDOTAJoinChatChannelResponse_SILENT_ERROR                     CMsgDOTAJoinChatChannelResponse_Result = 17
	CMsgDOTAJoinChatChannelResponse_NEW_PLAYER_USER_BANNED           CMsgDOTAJoinChatChannelResponse_Result = 18
)

var CMsgDOTAJoinChatChannelResponse_Result_name = map[int32]string{
	0:  "JOIN_SUCCESS",
	1:  "INVALID_CHANNEL_TYPE",
	2:  "ACCOUNT_NOT_FOUND",
	3:  "ACH_FAILED",
	4:  "USER_IN_TOO_MANY_CHANNELS",
	5:  "RATE_LIMIT_EXCEEDED",
	6:  "CHANNEL_FULL",
	7:  "CHANNEL_FULL_OVERFLOWED",
	8:  "FAILED_TO_ADD_USER",
	9:  "CHANNEL_TYPE_DISABLED",
	10: "PRIVATE_CHAT_CREATE_FAILED",
	11: "PRIVATE_CHAT_NO_PERMISSION",
	12: "PRIVATE_CHAT_CREATE_LOCK_FAILED",
	13: "PRIVATE_CHAT_KICKED",
	14: "USER_NOT_ALLOWED",
	15: "ENSURE_SPECIAL_PRIVILEGES_FAILED",
	16: "NEW_PLAYER_USER_NOT_ELIGIBLE",
	17: "SILENT_ERROR",
	18: "NEW_PLAYER_USER_BANNED",
}

var CMsgDOTAJoinChatChannelResponse_Result_value = map[string]int32{
	"JOIN_SUCCESS":                     0,
	"INVALID_CHANNEL_TYPE":             1,
	"ACCOUNT_NOT_FOUND":                2,
	"ACH_FAILED":                       3,
	"USER_IN_TOO_MANY_CHANNELS":        4,
	"RATE_LIMIT_EXCEEDED":              5,
	"CHANNEL_FULL":                     6,
	"CHANNEL_FULL_OVERFLOWED":          7,
	"FAILED_TO_ADD_USER":               8,
	"CHANNEL_TYPE_DISABLED":            9,
	"PRIVATE_CHAT_CREATE_FAILED":       10,
	"PRIVATE_CHAT_NO_PERMISSION":       11,
	"PRIVATE_CHAT_CREATE_LOCK_FAILED":  12,
	"PRIVATE_CHAT_KICKED":              13,
	"USER_NOT_ALLOWED":                 14,
	"ENSURE_SPECIAL_PRIVILEGES_FAILED": 15,
	"NEW_PLAYER_USER_NOT_ELIGIBLE":     16,
	"SILENT_ERROR":                     17,
	"NEW_PLAYER_USER_BANNED":           18,
}

func (x CMsgDOTAJoinChatChannelResponse_Result) Enum() *CMsgDOTAJoinChatChannelResponse_Result {
	p := new(CMsgDOTAJoinChatChannelResponse_Result)
	*p = x
	return p
}

func (x CMsgDOTAJoinChatChannelResponse_Result) String() string {
	return proto.EnumName(CMsgDOTAJoinChatChannelResponse_Result_name, int32(x))
}

func (x *CMsgDOTAJoinChatChannelResponse_Result) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgDOTAJoinChatChannelResponse_Result_value, data, "CMsgDOTAJoinChatChannelResponse_Result")
	if err != nil {
		return err
	}
	*x = CMsgDOTAJoinChatChannelResponse_Result(value)
	return nil
}

func (CMsgDOTAJoinChatChannelResponse_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{11, 0}
}

type CMsgClientToGCPrivateChatInvite struct {
	PrivateChatChannelName *string  `protobuf:"bytes,1,opt,name=private_chat_channel_name,json=privateChatChannelName" json:"private_chat_channel_name,omitempty"`
	InvitedAccountId       *uint32  `protobuf:"varint,2,opt,name=invited_account_id,json=invitedAccountId" json:"invited_account_id,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *CMsgClientToGCPrivateChatInvite) Reset()         { *m = CMsgClientToGCPrivateChatInvite{} }
func (m *CMsgClientToGCPrivateChatInvite) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCPrivateChatInvite) ProtoMessage()    {}
func (*CMsgClientToGCPrivateChatInvite) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{0}
}

func (m *CMsgClientToGCPrivateChatInvite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCPrivateChatInvite.Unmarshal(m, b)
}
func (m *CMsgClientToGCPrivateChatInvite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCPrivateChatInvite.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCPrivateChatInvite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCPrivateChatInvite.Merge(m, src)
}
func (m *CMsgClientToGCPrivateChatInvite) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCPrivateChatInvite.Size(m)
}
func (m *CMsgClientToGCPrivateChatInvite) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCPrivateChatInvite.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCPrivateChatInvite proto.InternalMessageInfo

func (m *CMsgClientToGCPrivateChatInvite) GetPrivateChatChannelName() string {
	if m != nil && m.PrivateChatChannelName != nil {
		return *m.PrivateChatChannelName
	}
	return ""
}

func (m *CMsgClientToGCPrivateChatInvite) GetInvitedAccountId() uint32 {
	if m != nil && m.InvitedAccountId != nil {
		return *m.InvitedAccountId
	}
	return 0
}

type CMsgClientToGCPrivateChatKick struct {
	PrivateChatChannelName *string  `protobuf:"bytes,1,opt,name=private_chat_channel_name,json=privateChatChannelName" json:"private_chat_channel_name,omitempty"`
	KickAccountId          *uint32  `protobuf:"varint,2,opt,name=kick_account_id,json=kickAccountId" json:"kick_account_id,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *CMsgClientToGCPrivateChatKick) Reset()         { *m = CMsgClientToGCPrivateChatKick{} }
func (m *CMsgClientToGCPrivateChatKick) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCPrivateChatKick) ProtoMessage()    {}
func (*CMsgClientToGCPrivateChatKick) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{1}
}

func (m *CMsgClientToGCPrivateChatKick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCPrivateChatKick.Unmarshal(m, b)
}
func (m *CMsgClientToGCPrivateChatKick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCPrivateChatKick.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCPrivateChatKick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCPrivateChatKick.Merge(m, src)
}
func (m *CMsgClientToGCPrivateChatKick) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCPrivateChatKick.Size(m)
}
func (m *CMsgClientToGCPrivateChatKick) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCPrivateChatKick.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCPrivateChatKick proto.InternalMessageInfo

func (m *CMsgClientToGCPrivateChatKick) GetPrivateChatChannelName() string {
	if m != nil && m.PrivateChatChannelName != nil {
		return *m.PrivateChatChannelName
	}
	return ""
}

func (m *CMsgClientToGCPrivateChatKick) GetKickAccountId() uint32 {
	if m != nil && m.KickAccountId != nil {
		return *m.KickAccountId
	}
	return 0
}

type CMsgClientToGCPrivateChatPromote struct {
	PrivateChatChannelName *string  `protobuf:"bytes,1,opt,name=private_chat_channel_name,json=privateChatChannelName" json:"private_chat_channel_name,omitempty"`
	PromoteAccountId       *uint32  `protobuf:"varint,2,opt,name=promote_account_id,json=promoteAccountId" json:"promote_account_id,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *CMsgClientToGCPrivateChatPromote) Reset()         { *m = CMsgClientToGCPrivateChatPromote{} }
func (m *CMsgClientToGCPrivateChatPromote) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCPrivateChatPromote) ProtoMessage()    {}
func (*CMsgClientToGCPrivateChatPromote) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{2}
}

func (m *CMsgClientToGCPrivateChatPromote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCPrivateChatPromote.Unmarshal(m, b)
}
func (m *CMsgClientToGCPrivateChatPromote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCPrivateChatPromote.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCPrivateChatPromote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCPrivateChatPromote.Merge(m, src)
}
func (m *CMsgClientToGCPrivateChatPromote) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCPrivateChatPromote.Size(m)
}
func (m *CMsgClientToGCPrivateChatPromote) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCPrivateChatPromote.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCPrivateChatPromote proto.InternalMessageInfo

func (m *CMsgClientToGCPrivateChatPromote) GetPrivateChatChannelName() string {
	if m != nil && m.PrivateChatChannelName != nil {
		return *m.PrivateChatChannelName
	}
	return ""
}

func (m *CMsgClientToGCPrivateChatPromote) GetPromoteAccountId() uint32 {
	if m != nil && m.PromoteAccountId != nil {
		return *m.PromoteAccountId
	}
	return 0
}

type CMsgClientToGCPrivateChatDemote struct {
	PrivateChatChannelName *string  `protobuf:"bytes,1,opt,name=private_chat_channel_name,json=privateChatChannelName" json:"private_chat_channel_name,omitempty"`
	DemoteAccountId        *uint32  `protobuf:"varint,2,opt,name=demote_account_id,json=demoteAccountId" json:"demote_account_id,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *CMsgClientToGCPrivateChatDemote) Reset()         { *m = CMsgClientToGCPrivateChatDemote{} }
func (m *CMsgClientToGCPrivateChatDemote) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCPrivateChatDemote) ProtoMessage()    {}
func (*CMsgClientToGCPrivateChatDemote) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{3}
}

func (m *CMsgClientToGCPrivateChatDemote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCPrivateChatDemote.Unmarshal(m, b)
}
func (m *CMsgClientToGCPrivateChatDemote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCPrivateChatDemote.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCPrivateChatDemote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCPrivateChatDemote.Merge(m, src)
}
func (m *CMsgClientToGCPrivateChatDemote) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCPrivateChatDemote.Size(m)
}
func (m *CMsgClientToGCPrivateChatDemote) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCPrivateChatDemote.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCPrivateChatDemote proto.InternalMessageInfo

func (m *CMsgClientToGCPrivateChatDemote) GetPrivateChatChannelName() string {
	if m != nil && m.PrivateChatChannelName != nil {
		return *m.PrivateChatChannelName
	}
	return ""
}

func (m *CMsgClientToGCPrivateChatDemote) GetDemoteAccountId() uint32 {
	if m != nil && m.DemoteAccountId != nil {
		return *m.DemoteAccountId
	}
	return 0
}

type CMsgGCToClientPrivateChatResponse struct {
	PrivateChatChannelName *string                                   `protobuf:"bytes,1,opt,name=private_chat_channel_name,json=privateChatChannelName" json:"private_chat_channel_name,omitempty"`
	Result                 *CMsgGCToClientPrivateChatResponse_Result `protobuf:"varint,2,opt,name=result,enum=protocol.CMsgGCToClientPrivateChatResponse_Result,def=0" json:"result,omitempty"`
	Username               *string                                   `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                                  `json:"-"`
	XXX_unrecognized       []byte                                    `json:"-"`
	XXX_sizecache          int32                                     `json:"-"`
}

func (m *CMsgGCToClientPrivateChatResponse) Reset()         { *m = CMsgGCToClientPrivateChatResponse{} }
func (m *CMsgGCToClientPrivateChatResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgGCToClientPrivateChatResponse) ProtoMessage()    {}
func (*CMsgGCToClientPrivateChatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{4}
}

func (m *CMsgGCToClientPrivateChatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGCToClientPrivateChatResponse.Unmarshal(m, b)
}
func (m *CMsgGCToClientPrivateChatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGCToClientPrivateChatResponse.Marshal(b, m, deterministic)
}
func (m *CMsgGCToClientPrivateChatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGCToClientPrivateChatResponse.Merge(m, src)
}
func (m *CMsgGCToClientPrivateChatResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgGCToClientPrivateChatResponse.Size(m)
}
func (m *CMsgGCToClientPrivateChatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGCToClientPrivateChatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGCToClientPrivateChatResponse proto.InternalMessageInfo

const Default_CMsgGCToClientPrivateChatResponse_Result CMsgGCToClientPrivateChatResponse_Result = CMsgGCToClientPrivateChatResponse_SUCCESS

func (m *CMsgGCToClientPrivateChatResponse) GetPrivateChatChannelName() string {
	if m != nil && m.PrivateChatChannelName != nil {
		return *m.PrivateChatChannelName
	}
	return ""
}

func (m *CMsgGCToClientPrivateChatResponse) GetResult() CMsgGCToClientPrivateChatResponse_Result {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return Default_CMsgGCToClientPrivateChatResponse_Result
}

func (m *CMsgGCToClientPrivateChatResponse) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

type CMsgDOTAJoinChatChannel struct {
	ChannelName          *string               `protobuf:"bytes,2,opt,name=channel_name,json=channelName" json:"channel_name,omitempty"`
	ChannelType          *DOTAChatChannelTypeT `protobuf:"varint,4,opt,name=channel_type,json=channelType,enum=protocol.DOTAChatChannelTypeT,def=0" json:"channel_type,omitempty"`
	SilentRejection      *bool                 `protobuf:"varint,5,opt,name=silent_rejection,json=silentRejection" json:"silent_rejection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CMsgDOTAJoinChatChannel) Reset()         { *m = CMsgDOTAJoinChatChannel{} }
func (m *CMsgDOTAJoinChatChannel) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAJoinChatChannel) ProtoMessage()    {}
func (*CMsgDOTAJoinChatChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{5}
}

func (m *CMsgDOTAJoinChatChannel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAJoinChatChannel.Unmarshal(m, b)
}
func (m *CMsgDOTAJoinChatChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAJoinChatChannel.Marshal(b, m, deterministic)
}
func (m *CMsgDOTAJoinChatChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAJoinChatChannel.Merge(m, src)
}
func (m *CMsgDOTAJoinChatChannel) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAJoinChatChannel.Size(m)
}
func (m *CMsgDOTAJoinChatChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAJoinChatChannel.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAJoinChatChannel proto.InternalMessageInfo

const Default_CMsgDOTAJoinChatChannel_ChannelType DOTAChatChannelTypeT = DOTAChatChannelTypeT_DOTAChannelType_Regional

func (m *CMsgDOTAJoinChatChannel) GetChannelName() string {
	if m != nil && m.ChannelName != nil {
		return *m.ChannelName
	}
	return ""
}

func (m *CMsgDOTAJoinChatChannel) GetChannelType() DOTAChatChannelTypeT {
	if m != nil && m.ChannelType != nil {
		return *m.ChannelType
	}
	return Default_CMsgDOTAJoinChatChannel_ChannelType
}

func (m *CMsgDOTAJoinChatChannel) GetSilentRejection() bool {
	if m != nil && m.SilentRejection != nil {
		return *m.SilentRejection
	}
	return false
}

type CMsgDOTALeaveChatChannel struct {
	ChannelId            *uint64  `protobuf:"varint,1,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgDOTALeaveChatChannel) Reset()         { *m = CMsgDOTALeaveChatChannel{} }
func (m *CMsgDOTALeaveChatChannel) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTALeaveChatChannel) ProtoMessage()    {}
func (*CMsgDOTALeaveChatChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{6}
}

func (m *CMsgDOTALeaveChatChannel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTALeaveChatChannel.Unmarshal(m, b)
}
func (m *CMsgDOTALeaveChatChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTALeaveChatChannel.Marshal(b, m, deterministic)
}
func (m *CMsgDOTALeaveChatChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTALeaveChatChannel.Merge(m, src)
}
func (m *CMsgDOTALeaveChatChannel) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTALeaveChatChannel.Size(m)
}
func (m *CMsgDOTALeaveChatChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTALeaveChatChannel.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTALeaveChatChannel proto.InternalMessageInfo

func (m *CMsgDOTALeaveChatChannel) GetChannelId() uint64 {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return 0
}

type CMsgGCChatReportPublicSpam struct {
	ChannelId            *uint64  `protobuf:"varint,1,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	ChannelUserId        *uint32  `protobuf:"varint,2,opt,name=channel_user_id,json=channelUserId" json:"channel_user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgGCChatReportPublicSpam) Reset()         { *m = CMsgGCChatReportPublicSpam{} }
func (m *CMsgGCChatReportPublicSpam) String() string { return proto.CompactTextString(m) }
func (*CMsgGCChatReportPublicSpam) ProtoMessage()    {}
func (*CMsgGCChatReportPublicSpam) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{7}
}

func (m *CMsgGCChatReportPublicSpam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGCChatReportPublicSpam.Unmarshal(m, b)
}
func (m *CMsgGCChatReportPublicSpam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGCChatReportPublicSpam.Marshal(b, m, deterministic)
}
func (m *CMsgGCChatReportPublicSpam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGCChatReportPublicSpam.Merge(m, src)
}
func (m *CMsgGCChatReportPublicSpam) XXX_Size() int {
	return xxx_messageInfo_CMsgGCChatReportPublicSpam.Size(m)
}
func (m *CMsgGCChatReportPublicSpam) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGCChatReportPublicSpam.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGCChatReportPublicSpam proto.InternalMessageInfo

func (m *CMsgGCChatReportPublicSpam) GetChannelId() uint64 {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return 0
}

func (m *CMsgGCChatReportPublicSpam) GetChannelUserId() uint32 {
	if m != nil && m.ChannelUserId != nil {
		return *m.ChannelUserId
	}
	return 0
}

type CMsgDOTAChatModeratorBan struct {
	ChannelId            *uint64  `protobuf:"varint,1,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	AccountId            *uint32  `protobuf:"varint,2,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	Duration             *uint32  `protobuf:"varint,3,opt,name=duration" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgDOTAChatModeratorBan) Reset()         { *m = CMsgDOTAChatModeratorBan{} }
func (m *CMsgDOTAChatModeratorBan) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAChatModeratorBan) ProtoMessage()    {}
func (*CMsgDOTAChatModeratorBan) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{8}
}

func (m *CMsgDOTAChatModeratorBan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAChatModeratorBan.Unmarshal(m, b)
}
func (m *CMsgDOTAChatModeratorBan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAChatModeratorBan.Marshal(b, m, deterministic)
}
func (m *CMsgDOTAChatModeratorBan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAChatModeratorBan.Merge(m, src)
}
func (m *CMsgDOTAChatModeratorBan) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAChatModeratorBan.Size(m)
}
func (m *CMsgDOTAChatModeratorBan) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAChatModeratorBan.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAChatModeratorBan proto.InternalMessageInfo

func (m *CMsgDOTAChatModeratorBan) GetChannelId() uint64 {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return 0
}

func (m *CMsgDOTAChatModeratorBan) GetAccountId() uint32 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *CMsgDOTAChatModeratorBan) GetDuration() uint32 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

type CMsgDOTAChatMessage struct {
	AccountId                   *uint32                              `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	ChannelId                   *uint64                              `protobuf:"varint,2,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	PersonaName                 *string                              `protobuf:"bytes,3,opt,name=persona_name,json=personaName" json:"persona_name,omitempty"`
	Text                        *string                              `protobuf:"bytes,4,opt,name=text" json:"text,omitempty"`
	Timestamp                   *uint32                              `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	SuggestInviteAccountId      *uint32                              `protobuf:"varint,6,opt,name=suggest_invite_account_id,json=suggestInviteAccountId" json:"suggest_invite_account_id,omitempty"`
	SuggestInviteName           *string                              `protobuf:"bytes,7,opt,name=suggest_invite_name,json=suggestInviteName" json:"suggest_invite_name,omitempty"`
	FantasyDraftOwnerAccountId  *uint32                              `protobuf:"varint,8,opt,name=fantasy_draft_owner_account_id,json=fantasyDraftOwnerAccountId" json:"fantasy_draft_owner_account_id,omitempty"`
	FantasyDraftPlayerAccountId *uint32                              `protobuf:"varint,9,opt,name=fantasy_draft_player_account_id,json=fantasyDraftPlayerAccountId" json:"fantasy_draft_player_account_id,omitempty"`
	EventId                     *uint32                              `protobuf:"varint,10,opt,name=event_id,json=eventId" json:"event_id,omitempty"`
	SuggestInviteToLobby        *bool                                `protobuf:"varint,11,opt,name=suggest_invite_to_lobby,json=suggestInviteToLobby" json:"suggest_invite_to_lobby,omitempty"`
	EventPoints                 *uint32                              `protobuf:"varint,12,opt,name=event_points,json=eventPoints" json:"event_points,omitempty"`
	CoinFlip                    *bool                                `protobuf:"varint,13,opt,name=coin_flip,json=coinFlip" json:"coin_flip,omitempty"`
	PlayerId                    *int32                               `protobuf:"varint,14,opt,name=player_id,json=playerId,def=-1" json:"player_id,omitempty"`
	ShareProfileAccountId       *uint32                              `protobuf:"varint,15,opt,name=share_profile_account_id,json=shareProfileAccountId" json:"share_profile_account_id,omitempty"`
	ChannelUserId               *uint32                              `protobuf:"varint,16,opt,name=channel_user_id,json=channelUserId" json:"channel_user_id,omitempty"`
	DiceRoll                    *CMsgDOTAChatMessage_DiceRoll        `protobuf:"bytes,17,opt,name=dice_roll,json=diceRoll" json:"dice_roll,omitempty"`
	SharePartyId                *uint64                              `protobuf:"varint,18,opt,name=share_party_id,json=sharePartyId" json:"share_party_id,omitempty"`
	ShareLobbyId                *uint64                              `protobuf:"varint,19,opt,name=share_lobby_id,json=shareLobbyId" json:"share_lobby_id,omitempty"`
	ShareLobbyCustomGameId      *uint64                              `protobuf:"varint,20,opt,name=share_lobby_custom_game_id,json=shareLobbyCustomGameId" json:"share_lobby_custom_game_id,omitempty"`
	ShareLobbyPasskey           *string                              `protobuf:"bytes,21,opt,name=share_lobby_passkey,json=shareLobbyPasskey" json:"share_lobby_passkey,omitempty"`
	PrivateChatChannelId        *uint32                              `protobuf:"varint,22,opt,name=private_chat_channel_id,json=privateChatChannelId" json:"private_chat_channel_id,omitempty"`
	Status                      *uint32                              `protobuf:"varint,23,opt,name=status" json:"status,omitempty"`
	LegacyBattleCupVictory      *bool                                `protobuf:"varint,24,opt,name=legacy_battle_cup_victory,json=legacyBattleCupVictory" json:"legacy_battle_cup_victory,omitempty"`
	BattleCupStreak             *uint32                              `protobuf:"varint,29,opt,name=battle_cup_streak,json=battleCupStreak" json:"battle_cup_streak,omitempty"`
	BadgeLevel                  *uint32                              `protobuf:"varint,25,opt,name=badge_level,json=badgeLevel" json:"badge_level,omitempty"`
	SuggestPickHeroId           *uint32                              `protobuf:"varint,26,opt,name=suggest_pick_hero_id,json=suggestPickHeroId" json:"suggest_pick_hero_id,omitempty"`
	SuggestPickHeroRole         *string                              `protobuf:"bytes,27,opt,name=suggest_pick_hero_role,json=suggestPickHeroRole" json:"suggest_pick_hero_role,omitempty"`
	SuggestBanHeroId            *uint32                              `protobuf:"varint,30,opt,name=suggest_ban_hero_id,json=suggestBanHeroId" json:"suggest_ban_hero_id,omitempty"`
	TriviaAnswer                *CMsgDOTAChatMessage_TriviaAnswered  `protobuf:"bytes,32,opt,name=trivia_answer,json=triviaAnswer" json:"trivia_answer,omitempty"`
	RequestedAbilityId          *int32                               `protobuf:"varint,33,opt,name=requested_ability_id,json=requestedAbilityId,def=-1" json:"requested_ability_id,omitempty"`
	ChatFlags                   *uint32                              `protobuf:"varint,34,opt,name=chat_flags,json=chatFlags" json:"chat_flags,omitempty"`
	StartedFindingMatch         *bool                                `protobuf:"varint,35,opt,name=started_finding_match,json=startedFindingMatch" json:"started_finding_match,omitempty"`
	CtrlIsDown                  *bool                                `protobuf:"varint,36,opt,name=ctrl_is_down,json=ctrlIsDown" json:"ctrl_is_down,omitempty"`
	FavoriteTeamId              *uint32                              `protobuf:"varint,37,opt,name=favorite_team_id,json=favoriteTeamId" json:"favorite_team_id,omitempty"`
	FavoriteTeamQuality         *uint32                              `protobuf:"varint,38,opt,name=favorite_team_quality,json=favoriteTeamQuality" json:"favorite_team_quality,omitempty"`
	SuggestPlayerDraftPick      *int32                               `protobuf:"varint,39,opt,name=suggest_player_draft_pick,json=suggestPlayerDraftPick,def=-1" json:"suggest_player_draft_pick,omitempty"`
	PlayerDraftPick             *CMsgDOTAChatMessage_PlayerDraftPick `protobuf:"bytes,40,opt,name=player_draft_pick,json=playerDraftPick" json:"player_draft_pick,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}                             `json:"-"`
	XXX_unrecognized            []byte                               `json:"-"`
	XXX_sizecache               int32                                `json:"-"`
}

func (m *CMsgDOTAChatMessage) Reset()         { *m = CMsgDOTAChatMessage{} }
func (m *CMsgDOTAChatMessage) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAChatMessage) ProtoMessage()    {}
func (*CMsgDOTAChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{9}
}

func (m *CMsgDOTAChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAChatMessage.Unmarshal(m, b)
}
func (m *CMsgDOTAChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAChatMessage.Marshal(b, m, deterministic)
}
func (m *CMsgDOTAChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAChatMessage.Merge(m, src)
}
func (m *CMsgDOTAChatMessage) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAChatMessage.Size(m)
}
func (m *CMsgDOTAChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAChatMessage proto.InternalMessageInfo

const Default_CMsgDOTAChatMessage_PlayerId int32 = -1
const Default_CMsgDOTAChatMessage_RequestedAbilityId int32 = -1
const Default_CMsgDOTAChatMessage_SuggestPlayerDraftPick int32 = -1

func (m *CMsgDOTAChatMessage) GetAccountId() uint32 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *CMsgDOTAChatMessage) GetChannelId() uint64 {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return 0
}

func (m *CMsgDOTAChatMessage) GetPersonaName() string {
	if m != nil && m.PersonaName != nil {
		return *m.PersonaName
	}
	return ""
}

func (m *CMsgDOTAChatMessage) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *CMsgDOTAChatMessage) GetTimestamp() uint32 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *CMsgDOTAChatMessage) GetSuggestInviteAccountId() uint32 {
	if m != nil && m.SuggestInviteAccountId != nil {
		return *m.SuggestInviteAccountId
	}
	return 0
}

func (m *CMsgDOTAChatMessage) GetSuggestInviteName() string {
	if m != nil && m.SuggestInviteName != nil {
		return *m.SuggestInviteName
	}
	return ""
}

func (m *CMsgDOTAChatMessage) GetFantasyDraftOwnerAccountId() uint32 {
	if m != nil && m.FantasyDraftOwnerAccountId != nil {
		return *m.FantasyDraftOwnerAccountId
	}
	return 0
}

func (m *CMsgDOTAChatMessage) GetFantasyDraftPlayerAccountId() uint32 {
	if m != nil && m.FantasyDraftPlayerAccountId != nil {
		return *m.FantasyDraftPlayerAccountId
	}
	return 0
}

func (m *CMsgDOTAChatMessage) GetEventId() uint32 {
	if m != nil && m.EventId != nil {
		return *m.EventId
	}
	return 0
}

func (m *CMsgDOTAChatMessage) GetSuggestInviteToLobby() bool {
	if m != nil && m.SuggestInviteToLobby != nil {
		return *m.SuggestInviteToLobby
	}
	return false
}

func (m *CMsgDOTAChatMessage) GetEventPoints() uint32 {
	if m != nil && m.EventPoints != nil {
		return *m.EventPoints
	}
	return 0
}

func (m *CMsgDOTAChatMessage) GetCoinFlip() bool {
	if m != nil && m.CoinFlip != nil {
		return *m.CoinFlip
	}
	return false
}

func (m *CMsgDOTAChatMessage) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return Default_CMsgDOTAChatMessage_PlayerId
}

func (m *CMsgDOTAChatMessage) GetShareProfileAccountId() uint32 {
	if m != nil && m.ShareProfileAccountId != nil {
		return *m.ShareProfileAccountId
	}
	return 0
}

func (m *CMsgDOTAChatMessage) GetChannelUserId() uint32 {
	if m != nil && m.ChannelUserId != nil {
		return *m.ChannelUserId
	}
	return 0
}

func (m *CMsgDOTAChatMessage) GetDiceRoll() *CMsgDOTAChatMessage_DiceRoll {
	if m != nil {
		return m.DiceRoll
	}
	return nil
}

func (m *CMsgDOTAChatMessage) GetSharePartyId() uint64 {
	if m != nil && m.SharePartyId != nil {
		return *m.SharePartyId
	}
	return 0
}

func (m *CMsgDOTAChatMessage) GetShareLobbyId() uint64 {
	if m != nil && m.ShareLobbyId != nil {
		return *m.ShareLobbyId
	}
	return 0
}

func (m *CMsgDOTAChatMessage) GetShareLobbyCustomGameId() uint64 {
	if m != nil && m.ShareLobbyCustomGameId != nil {
		return *m.ShareLobbyCustomGameId
	}
	return 0
}

func (m *CMsgDOTAChatMessage) GetShareLobbyPasskey() string {
	if m != nil && m.ShareLobbyPasskey != nil {
		return *m.ShareLobbyPasskey
	}
	return ""
}

func (m *CMsgDOTAChatMessage) GetPrivateChatChannelId() uint32 {
	if m != nil && m.PrivateChatChannelId != nil {
		return *m.PrivateChatChannelId
	}
	return 0
}

func (m *CMsgDOTAChatMessage) GetStatus() uint32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *CMsgDOTAChatMessage) GetLegacyBattleCupVictory() bool {
	if m != nil && m.LegacyBattleCupVictory != nil {
		return *m.LegacyBattleCupVictory
	}
	return false
}

func (m *CMsgDOTAChatMessage) GetBattleCupStreak() uint32 {
	if m != nil && m.BattleCupStreak != nil {
		return *m.BattleCupStreak
	}
	return 0
}

func (m *CMsgDOTAChatMessage) GetBadgeLevel() uint32 {
	if m != nil && m.BadgeLevel != nil {
		return *m.BadgeLevel
	}
	return 0
}

func (m *CMsgDOTAChatMessage) GetSuggestPickHeroId() uint32 {
	if m != nil && m.SuggestPickHeroId != nil {
		return *m.SuggestPickHeroId
	}
	return 0
}

func (m *CMsgDOTAChatMessage) GetSuggestPickHeroRole() string {
	if m != nil && m.SuggestPickHeroRole != nil {
		return *m.SuggestPickHeroRole
	}
	return ""
}

func (m *CMsgDOTAChatMessage) GetSuggestBanHeroId() uint32 {
	if m != nil && m.SuggestBanHeroId != nil {
		return *m.SuggestBanHeroId
	}
	return 0
}

func (m *CMsgDOTAChatMessage) GetTriviaAnswer() *CMsgDOTAChatMessage_TriviaAnswered {
	if m != nil {
		return m.TriviaAnswer
	}
	return nil
}

func (m *CMsgDOTAChatMessage) GetRequestedAbilityId() int32 {
	if m != nil && m.RequestedAbilityId != nil {
		return *m.RequestedAbilityId
	}
	return Default_CMsgDOTAChatMessage_RequestedAbilityId
}

func (m *CMsgDOTAChatMessage) GetChatFlags() uint32 {
	if m != nil && m.ChatFlags != nil {
		return *m.ChatFlags
	}
	return 0
}

func (m *CMsgDOTAChatMessage) GetStartedFindingMatch() bool {
	if m != nil && m.StartedFindingMatch != nil {
		return *m.StartedFindingMatch
	}
	return false
}

func (m *CMsgDOTAChatMessage) GetCtrlIsDown() bool {
	if m != nil && m.CtrlIsDown != nil {
		return *m.CtrlIsDown
	}
	return false
}

func (m *CMsgDOTAChatMessage) GetFavoriteTeamId() uint32 {
	if m != nil && m.FavoriteTeamId != nil {
		return *m.FavoriteTeamId
	}
	return 0
}

func (m *CMsgDOTAChatMessage) GetFavoriteTeamQuality() uint32 {
	if m != nil && m.FavoriteTeamQuality != nil {
		return *m.FavoriteTeamQuality
	}
	return 0
}

func (m *CMsgDOTAChatMessage) GetSuggestPlayerDraftPick() int32 {
	if m != nil && m.SuggestPlayerDraftPick != nil {
		return *m.SuggestPlayerDraftPick
	}
	return Default_CMsgDOTAChatMessage_SuggestPlayerDraftPick
}

func (m *CMsgDOTAChatMessage) GetPlayerDraftPick() *CMsgDOTAChatMessage_PlayerDraftPick {
	if m != nil {
		return m.PlayerDraftPick
	}
	return nil
}

type CMsgDOTAChatMessage_DiceRoll struct {
	RollMin              *int32   `protobuf:"varint,1,opt,name=roll_min,json=rollMin" json:"roll_min,omitempty"`
	RollMax              *int32   `protobuf:"varint,2,opt,name=roll_max,json=rollMax" json:"roll_max,omitempty"`
	Result               *int32   `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgDOTAChatMessage_DiceRoll) Reset()         { *m = CMsgDOTAChatMessage_DiceRoll{} }
func (m *CMsgDOTAChatMessage_DiceRoll) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAChatMessage_DiceRoll) ProtoMessage()    {}
func (*CMsgDOTAChatMessage_DiceRoll) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{9, 0}
}

func (m *CMsgDOTAChatMessage_DiceRoll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAChatMessage_DiceRoll.Unmarshal(m, b)
}
func (m *CMsgDOTAChatMessage_DiceRoll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAChatMessage_DiceRoll.Marshal(b, m, deterministic)
}
func (m *CMsgDOTAChatMessage_DiceRoll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAChatMessage_DiceRoll.Merge(m, src)
}
func (m *CMsgDOTAChatMessage_DiceRoll) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAChatMessage_DiceRoll.Size(m)
}
func (m *CMsgDOTAChatMessage_DiceRoll) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAChatMessage_DiceRoll.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAChatMessage_DiceRoll proto.InternalMessageInfo

func (m *CMsgDOTAChatMessage_DiceRoll) GetRollMin() int32 {
	if m != nil && m.RollMin != nil {
		return *m.RollMin
	}
	return 0
}

func (m *CMsgDOTAChatMessage_DiceRoll) GetRollMax() int32 {
	if m != nil && m.RollMax != nil {
		return *m.RollMax
	}
	return 0
}

func (m *CMsgDOTAChatMessage_DiceRoll) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type CMsgDOTAChatMessage_TriviaAnswered struct {
	QuestionId            *uint32  `protobuf:"varint,1,opt,name=question_id,json=questionId" json:"question_id,omitempty"`
	AnswerIndex           *uint32  `protobuf:"varint,2,opt,name=answer_index,json=answerIndex" json:"answer_index,omitempty"`
	PartyQuestionsCorrect *uint32  `protobuf:"varint,3,opt,name=party_questions_correct,json=partyQuestionsCorrect" json:"party_questions_correct,omitempty"`
	PartyQuestionsViewed  *uint32  `protobuf:"varint,4,opt,name=party_questions_viewed,json=partyQuestionsViewed" json:"party_questions_viewed,omitempty"`
	PartyTriviaPoints     *uint32  `protobuf:"varint,5,opt,name=party_trivia_points,json=partyTriviaPoints" json:"party_trivia_points,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *CMsgDOTAChatMessage_TriviaAnswered) Reset()         { *m = CMsgDOTAChatMessage_TriviaAnswered{} }
func (m *CMsgDOTAChatMessage_TriviaAnswered) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAChatMessage_TriviaAnswered) ProtoMessage()    {}
func (*CMsgDOTAChatMessage_TriviaAnswered) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{9, 1}
}

func (m *CMsgDOTAChatMessage_TriviaAnswered) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAChatMessage_TriviaAnswered.Unmarshal(m, b)
}
func (m *CMsgDOTAChatMessage_TriviaAnswered) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAChatMessage_TriviaAnswered.Marshal(b, m, deterministic)
}
func (m *CMsgDOTAChatMessage_TriviaAnswered) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAChatMessage_TriviaAnswered.Merge(m, src)
}
func (m *CMsgDOTAChatMessage_TriviaAnswered) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAChatMessage_TriviaAnswered.Size(m)
}
func (m *CMsgDOTAChatMessage_TriviaAnswered) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAChatMessage_TriviaAnswered.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAChatMessage_TriviaAnswered proto.InternalMessageInfo

func (m *CMsgDOTAChatMessage_TriviaAnswered) GetQuestionId() uint32 {
	if m != nil && m.QuestionId != nil {
		return *m.QuestionId
	}
	return 0
}

func (m *CMsgDOTAChatMessage_TriviaAnswered) GetAnswerIndex() uint32 {
	if m != nil && m.AnswerIndex != nil {
		return *m.AnswerIndex
	}
	return 0
}

func (m *CMsgDOTAChatMessage_TriviaAnswered) GetPartyQuestionsCorrect() uint32 {
	if m != nil && m.PartyQuestionsCorrect != nil {
		return *m.PartyQuestionsCorrect
	}
	return 0
}

func (m *CMsgDOTAChatMessage_TriviaAnswered) GetPartyQuestionsViewed() uint32 {
	if m != nil && m.PartyQuestionsViewed != nil {
		return *m.PartyQuestionsViewed
	}
	return 0
}

func (m *CMsgDOTAChatMessage_TriviaAnswered) GetPartyTriviaPoints() uint32 {
	if m != nil && m.PartyTriviaPoints != nil {
		return *m.PartyTriviaPoints
	}
	return 0
}

type CMsgDOTAChatMessage_PlayerDraftPick struct {
	PlayerId             *int32   `protobuf:"varint,1,opt,name=player_id,json=playerId,def=-1" json:"player_id,omitempty"`
	Team                 *int32   `protobuf:"varint,2,opt,name=team" json:"team,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgDOTAChatMessage_PlayerDraftPick) Reset()         { *m = CMsgDOTAChatMessage_PlayerDraftPick{} }
func (m *CMsgDOTAChatMessage_PlayerDraftPick) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAChatMessage_PlayerDraftPick) ProtoMessage()    {}
func (*CMsgDOTAChatMessage_PlayerDraftPick) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{9, 2}
}

func (m *CMsgDOTAChatMessage_PlayerDraftPick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAChatMessage_PlayerDraftPick.Unmarshal(m, b)
}
func (m *CMsgDOTAChatMessage_PlayerDraftPick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAChatMessage_PlayerDraftPick.Marshal(b, m, deterministic)
}
func (m *CMsgDOTAChatMessage_PlayerDraftPick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAChatMessage_PlayerDraftPick.Merge(m, src)
}
func (m *CMsgDOTAChatMessage_PlayerDraftPick) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAChatMessage_PlayerDraftPick.Size(m)
}
func (m *CMsgDOTAChatMessage_PlayerDraftPick) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAChatMessage_PlayerDraftPick.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAChatMessage_PlayerDraftPick proto.InternalMessageInfo

const Default_CMsgDOTAChatMessage_PlayerDraftPick_PlayerId int32 = -1

func (m *CMsgDOTAChatMessage_PlayerDraftPick) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return Default_CMsgDOTAChatMessage_PlayerDraftPick_PlayerId
}

func (m *CMsgDOTAChatMessage_PlayerDraftPick) GetTeam() int32 {
	if m != nil && m.Team != nil {
		return *m.Team
	}
	return 0
}

type CMsgDOTAChatMember struct {
	SteamId              *uint64  `protobuf:"fixed64,1,opt,name=steam_id,json=steamId" json:"steam_id,omitempty"`
	PersonaName          *string  `protobuf:"bytes,2,opt,name=persona_name,json=personaName" json:"persona_name,omitempty"`
	ChannelUserId        *uint32  `protobuf:"varint,3,opt,name=channel_user_id,json=channelUserId" json:"channel_user_id,omitempty"`
	Status               *uint32  `protobuf:"varint,4,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgDOTAChatMember) Reset()         { *m = CMsgDOTAChatMember{} }
func (m *CMsgDOTAChatMember) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAChatMember) ProtoMessage()    {}
func (*CMsgDOTAChatMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{10}
}

func (m *CMsgDOTAChatMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAChatMember.Unmarshal(m, b)
}
func (m *CMsgDOTAChatMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAChatMember.Marshal(b, m, deterministic)
}
func (m *CMsgDOTAChatMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAChatMember.Merge(m, src)
}
func (m *CMsgDOTAChatMember) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAChatMember.Size(m)
}
func (m *CMsgDOTAChatMember) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAChatMember.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAChatMember proto.InternalMessageInfo

func (m *CMsgDOTAChatMember) GetSteamId() uint64 {
	if m != nil && m.SteamId != nil {
		return *m.SteamId
	}
	return 0
}

func (m *CMsgDOTAChatMember) GetPersonaName() string {
	if m != nil && m.PersonaName != nil {
		return *m.PersonaName
	}
	return ""
}

func (m *CMsgDOTAChatMember) GetChannelUserId() uint32 {
	if m != nil && m.ChannelUserId != nil {
		return *m.ChannelUserId
	}
	return 0
}

func (m *CMsgDOTAChatMember) GetStatus() uint32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

type CMsgDOTAJoinChatChannelResponse struct {
	Response             *uint32                                 `protobuf:"varint,1,opt,name=response" json:"response,omitempty"`
	ChannelName          *string                                 `protobuf:"bytes,2,opt,name=channel_name,json=channelName" json:"channel_name,omitempty"`
	ChannelId            *uint64                                 `protobuf:"fixed64,3,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	MaxMembers           *uint32                                 `protobuf:"varint,4,opt,name=max_members,json=maxMembers" json:"max_members,omitempty"`
	Members              []*CMsgDOTAChatMember                   `protobuf:"bytes,5,rep,name=members" json:"members,omitempty"`
	ChannelType          *DOTAChatChannelTypeT                   `protobuf:"varint,6,opt,name=channel_type,json=channelType,enum=protocol.DOTAChatChannelTypeT,def=0" json:"channel_type,omitempty"`
	Result               *CMsgDOTAJoinChatChannelResponse_Result `protobuf:"varint,7,opt,name=result,enum=protocol.CMsgDOTAJoinChatChannelResponse_Result,def=0" json:"result,omitempty"`
	GcInitiatedJoin      *bool                                   `protobuf:"varint,8,opt,name=gc_initiated_join,json=gcInitiatedJoin" json:"gc_initiated_join,omitempty"`
	ChannelUserId        *uint32                                 `protobuf:"varint,9,opt,name=channel_user_id,json=channelUserId" json:"channel_user_id,omitempty"`
	WelcomeMessage       *string                                 `protobuf:"bytes,10,opt,name=welcome_message,json=welcomeMessage" json:"welcome_message,omitempty"`
	SpecialPrivileges    *EChatSpecialPrivileges                 `protobuf:"varint,11,opt,name=special_privileges,json=specialPrivileges,enum=protocol.EChatSpecialPrivileges,def=0" json:"special_privileges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *CMsgDOTAJoinChatChannelResponse) Reset()         { *m = CMsgDOTAJoinChatChannelResponse{} }
func (m *CMsgDOTAJoinChatChannelResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAJoinChatChannelResponse) ProtoMessage()    {}
func (*CMsgDOTAJoinChatChannelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{11}
}

func (m *CMsgDOTAJoinChatChannelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAJoinChatChannelResponse.Unmarshal(m, b)
}
func (m *CMsgDOTAJoinChatChannelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAJoinChatChannelResponse.Marshal(b, m, deterministic)
}
func (m *CMsgDOTAJoinChatChannelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAJoinChatChannelResponse.Merge(m, src)
}
func (m *CMsgDOTAJoinChatChannelResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAJoinChatChannelResponse.Size(m)
}
func (m *CMsgDOTAJoinChatChannelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAJoinChatChannelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAJoinChatChannelResponse proto.InternalMessageInfo

const Default_CMsgDOTAJoinChatChannelResponse_ChannelType DOTAChatChannelTypeT = DOTAChatChannelTypeT_DOTAChannelType_Regional
const Default_CMsgDOTAJoinChatChannelResponse_Result CMsgDOTAJoinChatChannelResponse_Result = CMsgDOTAJoinChatChannelResponse_JOIN_SUCCESS
const Default_CMsgDOTAJoinChatChannelResponse_SpecialPrivileges EChatSpecialPrivileges = EChatSpecialPrivileges_k_EChatSpecialPrivileges_None

func (m *CMsgDOTAJoinChatChannelResponse) GetResponse() uint32 {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return 0
}

func (m *CMsgDOTAJoinChatChannelResponse) GetChannelName() string {
	if m != nil && m.ChannelName != nil {
		return *m.ChannelName
	}
	return ""
}

func (m *CMsgDOTAJoinChatChannelResponse) GetChannelId() uint64 {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return 0
}

func (m *CMsgDOTAJoinChatChannelResponse) GetMaxMembers() uint32 {
	if m != nil && m.MaxMembers != nil {
		return *m.MaxMembers
	}
	return 0
}

func (m *CMsgDOTAJoinChatChannelResponse) GetMembers() []*CMsgDOTAChatMember {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *CMsgDOTAJoinChatChannelResponse) GetChannelType() DOTAChatChannelTypeT {
	if m != nil && m.ChannelType != nil {
		return *m.ChannelType
	}
	return Default_CMsgDOTAJoinChatChannelResponse_ChannelType
}

func (m *CMsgDOTAJoinChatChannelResponse) GetResult() CMsgDOTAJoinChatChannelResponse_Result {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return Default_CMsgDOTAJoinChatChannelResponse_Result
}

func (m *CMsgDOTAJoinChatChannelResponse) GetGcInitiatedJoin() bool {
	if m != nil && m.GcInitiatedJoin != nil {
		return *m.GcInitiatedJoin
	}
	return false
}

func (m *CMsgDOTAJoinChatChannelResponse) GetChannelUserId() uint32 {
	if m != nil && m.ChannelUserId != nil {
		return *m.ChannelUserId
	}
	return 0
}

func (m *CMsgDOTAJoinChatChannelResponse) GetWelcomeMessage() string {
	if m != nil && m.WelcomeMessage != nil {
		return *m.WelcomeMessage
	}
	return ""
}

func (m *CMsgDOTAJoinChatChannelResponse) GetSpecialPrivileges() EChatSpecialPrivileges {
	if m != nil && m.SpecialPrivileges != nil {
		return *m.SpecialPrivileges
	}
	return Default_CMsgDOTAJoinChatChannelResponse_SpecialPrivileges
}

type CMsgDOTAOtherJoinedChatChannel struct {
	ChannelId            *uint64  `protobuf:"fixed64,1,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	PersonaName          *string  `protobuf:"bytes,2,opt,name=persona_name,json=personaName" json:"persona_name,omitempty"`
	SteamId              *uint64  `protobuf:"fixed64,3,opt,name=steam_id,json=steamId" json:"steam_id,omitempty"`
	ChannelUserId        *uint32  `protobuf:"varint,4,opt,name=channel_user_id,json=channelUserId" json:"channel_user_id,omitempty"`
	Status               *uint32  `protobuf:"varint,5,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgDOTAOtherJoinedChatChannel) Reset()         { *m = CMsgDOTAOtherJoinedChatChannel{} }
func (m *CMsgDOTAOtherJoinedChatChannel) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAOtherJoinedChatChannel) ProtoMessage()    {}
func (*CMsgDOTAOtherJoinedChatChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{12}
}

func (m *CMsgDOTAOtherJoinedChatChannel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAOtherJoinedChatChannel.Unmarshal(m, b)
}
func (m *CMsgDOTAOtherJoinedChatChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAOtherJoinedChatChannel.Marshal(b, m, deterministic)
}
func (m *CMsgDOTAOtherJoinedChatChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAOtherJoinedChatChannel.Merge(m, src)
}
func (m *CMsgDOTAOtherJoinedChatChannel) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAOtherJoinedChatChannel.Size(m)
}
func (m *CMsgDOTAOtherJoinedChatChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAOtherJoinedChatChannel.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAOtherJoinedChatChannel proto.InternalMessageInfo

func (m *CMsgDOTAOtherJoinedChatChannel) GetChannelId() uint64 {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return 0
}

func (m *CMsgDOTAOtherJoinedChatChannel) GetPersonaName() string {
	if m != nil && m.PersonaName != nil {
		return *m.PersonaName
	}
	return ""
}

func (m *CMsgDOTAOtherJoinedChatChannel) GetSteamId() uint64 {
	if m != nil && m.SteamId != nil {
		return *m.SteamId
	}
	return 0
}

func (m *CMsgDOTAOtherJoinedChatChannel) GetChannelUserId() uint32 {
	if m != nil && m.ChannelUserId != nil {
		return *m.ChannelUserId
	}
	return 0
}

func (m *CMsgDOTAOtherJoinedChatChannel) GetStatus() uint32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

type CMsgDOTAOtherLeftChatChannel struct {
	ChannelId            *uint64  `protobuf:"fixed64,1,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	SteamId              *uint64  `protobuf:"fixed64,2,opt,name=steam_id,json=steamId" json:"steam_id,omitempty"`
	ChannelUserId        *uint32  `protobuf:"varint,3,opt,name=channel_user_id,json=channelUserId" json:"channel_user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgDOTAOtherLeftChatChannel) Reset()         { *m = CMsgDOTAOtherLeftChatChannel{} }
func (m *CMsgDOTAOtherLeftChatChannel) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAOtherLeftChatChannel) ProtoMessage()    {}
func (*CMsgDOTAOtherLeftChatChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{13}
}

func (m *CMsgDOTAOtherLeftChatChannel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAOtherLeftChatChannel.Unmarshal(m, b)
}
func (m *CMsgDOTAOtherLeftChatChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAOtherLeftChatChannel.Marshal(b, m, deterministic)
}
func (m *CMsgDOTAOtherLeftChatChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAOtherLeftChatChannel.Merge(m, src)
}
func (m *CMsgDOTAOtherLeftChatChannel) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAOtherLeftChatChannel.Size(m)
}
func (m *CMsgDOTAOtherLeftChatChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAOtherLeftChatChannel.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAOtherLeftChatChannel proto.InternalMessageInfo

func (m *CMsgDOTAOtherLeftChatChannel) GetChannelId() uint64 {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return 0
}

func (m *CMsgDOTAOtherLeftChatChannel) GetSteamId() uint64 {
	if m != nil && m.SteamId != nil {
		return *m.SteamId
	}
	return 0
}

func (m *CMsgDOTAOtherLeftChatChannel) GetChannelUserId() uint32 {
	if m != nil && m.ChannelUserId != nil {
		return *m.ChannelUserId
	}
	return 0
}

type CMsgDOTARequestChatChannelList struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgDOTARequestChatChannelList) Reset()         { *m = CMsgDOTARequestChatChannelList{} }
func (m *CMsgDOTARequestChatChannelList) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTARequestChatChannelList) ProtoMessage()    {}
func (*CMsgDOTARequestChatChannelList) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{14}
}

func (m *CMsgDOTARequestChatChannelList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTARequestChatChannelList.Unmarshal(m, b)
}
func (m *CMsgDOTARequestChatChannelList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTARequestChatChannelList.Marshal(b, m, deterministic)
}
func (m *CMsgDOTARequestChatChannelList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTARequestChatChannelList.Merge(m, src)
}
func (m *CMsgDOTARequestChatChannelList) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTARequestChatChannelList.Size(m)
}
func (m *CMsgDOTARequestChatChannelList) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTARequestChatChannelList.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTARequestChatChannelList proto.InternalMessageInfo

type CMsgDOTARequestChatChannelListResponse struct {
	Channels             []*CMsgDOTARequestChatChannelListResponse_ChatChannel `protobuf:"bytes,1,rep,name=channels" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                              `json:"-"`
	XXX_unrecognized     []byte                                                `json:"-"`
	XXX_sizecache        int32                                                 `json:"-"`
}

func (m *CMsgDOTARequestChatChannelListResponse) Reset() {
	*m = CMsgDOTARequestChatChannelListResponse{}
}
func (m *CMsgDOTARequestChatChannelListResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTARequestChatChannelListResponse) ProtoMessage()    {}
func (*CMsgDOTARequestChatChannelListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{15}
}

func (m *CMsgDOTARequestChatChannelListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTARequestChatChannelListResponse.Unmarshal(m, b)
}
func (m *CMsgDOTARequestChatChannelListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTARequestChatChannelListResponse.Marshal(b, m, deterministic)
}
func (m *CMsgDOTARequestChatChannelListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTARequestChatChannelListResponse.Merge(m, src)
}
func (m *CMsgDOTARequestChatChannelListResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTARequestChatChannelListResponse.Size(m)
}
func (m *CMsgDOTARequestChatChannelListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTARequestChatChannelListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTARequestChatChannelListResponse proto.InternalMessageInfo

func (m *CMsgDOTARequestChatChannelListResponse) GetChannels() []*CMsgDOTARequestChatChannelListResponse_ChatChannel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type CMsgDOTARequestChatChannelListResponse_ChatChannel struct {
	ChannelName          *string               `protobuf:"bytes,1,opt,name=channel_name,json=channelName" json:"channel_name,omitempty"`
	NumMembers           *uint32               `protobuf:"varint,2,opt,name=num_members,json=numMembers" json:"num_members,omitempty"`
	ChannelType          *DOTAChatChannelTypeT `protobuf:"varint,3,opt,name=channel_type,json=channelType,enum=protocol.DOTAChatChannelTypeT,def=0" json:"channel_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CMsgDOTARequestChatChannelListResponse_ChatChannel) Reset() {
	*m = CMsgDOTARequestChatChannelListResponse_ChatChannel{}
}
func (m *CMsgDOTARequestChatChannelListResponse_ChatChannel) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgDOTARequestChatChannelListResponse_ChatChannel) ProtoMessage() {}
func (*CMsgDOTARequestChatChannelListResponse_ChatChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{15, 0}
}

func (m *CMsgDOTARequestChatChannelListResponse_ChatChannel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTARequestChatChannelListResponse_ChatChannel.Unmarshal(m, b)
}
func (m *CMsgDOTARequestChatChannelListResponse_ChatChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTARequestChatChannelListResponse_ChatChannel.Marshal(b, m, deterministic)
}
func (m *CMsgDOTARequestChatChannelListResponse_ChatChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTARequestChatChannelListResponse_ChatChannel.Merge(m, src)
}
func (m *CMsgDOTARequestChatChannelListResponse_ChatChannel) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTARequestChatChannelListResponse_ChatChannel.Size(m)
}
func (m *CMsgDOTARequestChatChannelListResponse_ChatChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTARequestChatChannelListResponse_ChatChannel.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTARequestChatChannelListResponse_ChatChannel proto.InternalMessageInfo

const Default_CMsgDOTARequestChatChannelListResponse_ChatChannel_ChannelType DOTAChatChannelTypeT = DOTAChatChannelTypeT_DOTAChannelType_Regional

func (m *CMsgDOTARequestChatChannelListResponse_ChatChannel) GetChannelName() string {
	if m != nil && m.ChannelName != nil {
		return *m.ChannelName
	}
	return ""
}

func (m *CMsgDOTARequestChatChannelListResponse_ChatChannel) GetNumMembers() uint32 {
	if m != nil && m.NumMembers != nil {
		return *m.NumMembers
	}
	return 0
}

func (m *CMsgDOTARequestChatChannelListResponse_ChatChannel) GetChannelType() DOTAChatChannelTypeT {
	if m != nil && m.ChannelType != nil {
		return *m.ChannelType
	}
	return Default_CMsgDOTARequestChatChannelListResponse_ChatChannel_ChannelType
}

type CMsgDOTAChatGetUserListResponse struct {
	ChannelId            *uint64                                   `protobuf:"fixed64,1,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	Members              []*CMsgDOTAChatGetUserListResponse_Member `protobuf:"bytes,2,rep,name=members" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *CMsgDOTAChatGetUserListResponse) Reset()         { *m = CMsgDOTAChatGetUserListResponse{} }
func (m *CMsgDOTAChatGetUserListResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAChatGetUserListResponse) ProtoMessage()    {}
func (*CMsgDOTAChatGetUserListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{16}
}

func (m *CMsgDOTAChatGetUserListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAChatGetUserListResponse.Unmarshal(m, b)
}
func (m *CMsgDOTAChatGetUserListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAChatGetUserListResponse.Marshal(b, m, deterministic)
}
func (m *CMsgDOTAChatGetUserListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAChatGetUserListResponse.Merge(m, src)
}
func (m *CMsgDOTAChatGetUserListResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAChatGetUserListResponse.Size(m)
}
func (m *CMsgDOTAChatGetUserListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAChatGetUserListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAChatGetUserListResponse proto.InternalMessageInfo

func (m *CMsgDOTAChatGetUserListResponse) GetChannelId() uint64 {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return 0
}

func (m *CMsgDOTAChatGetUserListResponse) GetMembers() []*CMsgDOTAChatGetUserListResponse_Member {
	if m != nil {
		return m.Members
	}
	return nil
}

type CMsgDOTAChatGetUserListResponse_Member struct {
	SteamId              *uint64  `protobuf:"fixed64,1,opt,name=steam_id,json=steamId" json:"steam_id,omitempty"`
	PersonaName          *string  `protobuf:"bytes,2,opt,name=persona_name,json=personaName" json:"persona_name,omitempty"`
	ChannelUserId        *uint32  `protobuf:"varint,3,opt,name=channel_user_id,json=channelUserId" json:"channel_user_id,omitempty"`
	Status               *uint32  `protobuf:"varint,4,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgDOTAChatGetUserListResponse_Member) Reset() {
	*m = CMsgDOTAChatGetUserListResponse_Member{}
}
func (m *CMsgDOTAChatGetUserListResponse_Member) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAChatGetUserListResponse_Member) ProtoMessage()    {}
func (*CMsgDOTAChatGetUserListResponse_Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{16, 0}
}

func (m *CMsgDOTAChatGetUserListResponse_Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAChatGetUserListResponse_Member.Unmarshal(m, b)
}
func (m *CMsgDOTAChatGetUserListResponse_Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAChatGetUserListResponse_Member.Marshal(b, m, deterministic)
}
func (m *CMsgDOTAChatGetUserListResponse_Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAChatGetUserListResponse_Member.Merge(m, src)
}
func (m *CMsgDOTAChatGetUserListResponse_Member) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAChatGetUserListResponse_Member.Size(m)
}
func (m *CMsgDOTAChatGetUserListResponse_Member) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAChatGetUserListResponse_Member.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAChatGetUserListResponse_Member proto.InternalMessageInfo

func (m *CMsgDOTAChatGetUserListResponse_Member) GetSteamId() uint64 {
	if m != nil && m.SteamId != nil {
		return *m.SteamId
	}
	return 0
}

func (m *CMsgDOTAChatGetUserListResponse_Member) GetPersonaName() string {
	if m != nil && m.PersonaName != nil {
		return *m.PersonaName
	}
	return ""
}

func (m *CMsgDOTAChatGetUserListResponse_Member) GetChannelUserId() uint32 {
	if m != nil && m.ChannelUserId != nil {
		return *m.ChannelUserId
	}
	return 0
}

func (m *CMsgDOTAChatGetUserListResponse_Member) GetStatus() uint32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

type CMsgDOTAChatGetMemberCount struct {
	ChannelName          *string               `protobuf:"bytes,1,opt,name=channel_name,json=channelName" json:"channel_name,omitempty"`
	ChannelType          *DOTAChatChannelTypeT `protobuf:"varint,2,opt,name=channel_type,json=channelType,enum=protocol.DOTAChatChannelTypeT,def=0" json:"channel_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CMsgDOTAChatGetMemberCount) Reset()         { *m = CMsgDOTAChatGetMemberCount{} }
func (m *CMsgDOTAChatGetMemberCount) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAChatGetMemberCount) ProtoMessage()    {}
func (*CMsgDOTAChatGetMemberCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{17}
}

func (m *CMsgDOTAChatGetMemberCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAChatGetMemberCount.Unmarshal(m, b)
}
func (m *CMsgDOTAChatGetMemberCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAChatGetMemberCount.Marshal(b, m, deterministic)
}
func (m *CMsgDOTAChatGetMemberCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAChatGetMemberCount.Merge(m, src)
}
func (m *CMsgDOTAChatGetMemberCount) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAChatGetMemberCount.Size(m)
}
func (m *CMsgDOTAChatGetMemberCount) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAChatGetMemberCount.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAChatGetMemberCount proto.InternalMessageInfo

const Default_CMsgDOTAChatGetMemberCount_ChannelType DOTAChatChannelTypeT = DOTAChatChannelTypeT_DOTAChannelType_Regional

func (m *CMsgDOTAChatGetMemberCount) GetChannelName() string {
	if m != nil && m.ChannelName != nil {
		return *m.ChannelName
	}
	return ""
}

func (m *CMsgDOTAChatGetMemberCount) GetChannelType() DOTAChatChannelTypeT {
	if m != nil && m.ChannelType != nil {
		return *m.ChannelType
	}
	return Default_CMsgDOTAChatGetMemberCount_ChannelType
}

type CMsgDOTAChatGetMemberCountResponse struct {
	ChannelName          *string               `protobuf:"bytes,1,opt,name=channel_name,json=channelName" json:"channel_name,omitempty"`
	ChannelType          *DOTAChatChannelTypeT `protobuf:"varint,2,opt,name=channel_type,json=channelType,enum=protocol.DOTAChatChannelTypeT,def=0" json:"channel_type,omitempty"`
	MemberCount          *uint32               `protobuf:"varint,3,opt,name=member_count,json=memberCount" json:"member_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CMsgDOTAChatGetMemberCountResponse) Reset()         { *m = CMsgDOTAChatGetMemberCountResponse{} }
func (m *CMsgDOTAChatGetMemberCountResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAChatGetMemberCountResponse) ProtoMessage()    {}
func (*CMsgDOTAChatGetMemberCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{18}
}

func (m *CMsgDOTAChatGetMemberCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAChatGetMemberCountResponse.Unmarshal(m, b)
}
func (m *CMsgDOTAChatGetMemberCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAChatGetMemberCountResponse.Marshal(b, m, deterministic)
}
func (m *CMsgDOTAChatGetMemberCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAChatGetMemberCountResponse.Merge(m, src)
}
func (m *CMsgDOTAChatGetMemberCountResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAChatGetMemberCountResponse.Size(m)
}
func (m *CMsgDOTAChatGetMemberCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAChatGetMemberCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAChatGetMemberCountResponse proto.InternalMessageInfo

const Default_CMsgDOTAChatGetMemberCountResponse_ChannelType DOTAChatChannelTypeT = DOTAChatChannelTypeT_DOTAChannelType_Regional

func (m *CMsgDOTAChatGetMemberCountResponse) GetChannelName() string {
	if m != nil && m.ChannelName != nil {
		return *m.ChannelName
	}
	return ""
}

func (m *CMsgDOTAChatGetMemberCountResponse) GetChannelType() DOTAChatChannelTypeT {
	if m != nil && m.ChannelType != nil {
		return *m.ChannelType
	}
	return Default_CMsgDOTAChatGetMemberCountResponse_ChannelType
}

func (m *CMsgDOTAChatGetMemberCountResponse) GetMemberCount() uint32 {
	if m != nil && m.MemberCount != nil {
		return *m.MemberCount
	}
	return 0
}

type CMsgDOTAChatRegionsEnabled struct {
	EnableAllRegions     *bool                                `protobuf:"varint,1,opt,name=enable_all_regions,json=enableAllRegions" json:"enable_all_regions,omitempty"`
	EnabledRegions       []*CMsgDOTAChatRegionsEnabled_Region `protobuf:"bytes,2,rep,name=enabled_regions,json=enabledRegions" json:"enabled_regions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *CMsgDOTAChatRegionsEnabled) Reset()         { *m = CMsgDOTAChatRegionsEnabled{} }
func (m *CMsgDOTAChatRegionsEnabled) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAChatRegionsEnabled) ProtoMessage()    {}
func (*CMsgDOTAChatRegionsEnabled) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{19}
}

func (m *CMsgDOTAChatRegionsEnabled) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAChatRegionsEnabled.Unmarshal(m, b)
}
func (m *CMsgDOTAChatRegionsEnabled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAChatRegionsEnabled.Marshal(b, m, deterministic)
}
func (m *CMsgDOTAChatRegionsEnabled) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAChatRegionsEnabled.Merge(m, src)
}
func (m *CMsgDOTAChatRegionsEnabled) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAChatRegionsEnabled.Size(m)
}
func (m *CMsgDOTAChatRegionsEnabled) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAChatRegionsEnabled.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAChatRegionsEnabled proto.InternalMessageInfo

func (m *CMsgDOTAChatRegionsEnabled) GetEnableAllRegions() bool {
	if m != nil && m.EnableAllRegions != nil {
		return *m.EnableAllRegions
	}
	return false
}

func (m *CMsgDOTAChatRegionsEnabled) GetEnabledRegions() []*CMsgDOTAChatRegionsEnabled_Region {
	if m != nil {
		return m.EnabledRegions
	}
	return nil
}

type CMsgDOTAChatRegionsEnabled_Region struct {
	MinLatitude          *float32 `protobuf:"fixed32,1,opt,name=min_latitude,json=minLatitude" json:"min_latitude,omitempty"`
	MaxLatitude          *float32 `protobuf:"fixed32,2,opt,name=max_latitude,json=maxLatitude" json:"max_latitude,omitempty"`
	MinLongitude         *float32 `protobuf:"fixed32,3,opt,name=min_longitude,json=minLongitude" json:"min_longitude,omitempty"`
	MaxLongitude         *float32 `protobuf:"fixed32,4,opt,name=max_longitude,json=maxLongitude" json:"max_longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgDOTAChatRegionsEnabled_Region) Reset()         { *m = CMsgDOTAChatRegionsEnabled_Region{} }
func (m *CMsgDOTAChatRegionsEnabled_Region) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAChatRegionsEnabled_Region) ProtoMessage()    {}
func (*CMsgDOTAChatRegionsEnabled_Region) Descriptor() ([]byte, []int) {
	return fileDescriptor_56aef27c555bd81b, []int{19, 0}
}

func (m *CMsgDOTAChatRegionsEnabled_Region) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAChatRegionsEnabled_Region.Unmarshal(m, b)
}
func (m *CMsgDOTAChatRegionsEnabled_Region) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAChatRegionsEnabled_Region.Marshal(b, m, deterministic)
}
func (m *CMsgDOTAChatRegionsEnabled_Region) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAChatRegionsEnabled_Region.Merge(m, src)
}
func (m *CMsgDOTAChatRegionsEnabled_Region) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAChatRegionsEnabled_Region.Size(m)
}
func (m *CMsgDOTAChatRegionsEnabled_Region) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAChatRegionsEnabled_Region.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAChatRegionsEnabled_Region proto.InternalMessageInfo

func (m *CMsgDOTAChatRegionsEnabled_Region) GetMinLatitude() float32 {
	if m != nil && m.MinLatitude != nil {
		return *m.MinLatitude
	}
	return 0
}

func (m *CMsgDOTAChatRegionsEnabled_Region) GetMaxLatitude() float32 {
	if m != nil && m.MaxLatitude != nil {
		return *m.MaxLatitude
	}
	return 0
}

func (m *CMsgDOTAChatRegionsEnabled_Region) GetMinLongitude() float32 {
	if m != nil && m.MinLongitude != nil {
		return *m.MinLongitude
	}
	return 0
}

func (m *CMsgDOTAChatRegionsEnabled_Region) GetMaxLongitude() float32 {
	if m != nil && m.MaxLongitude != nil {
		return *m.MaxLongitude
	}
	return 0
}

func init() {
	proto.RegisterEnum("protocol.CMsgGCToClientPrivateChatResponse_Result", CMsgGCToClientPrivateChatResponse_Result_name, CMsgGCToClientPrivateChatResponse_Result_value)
	proto.RegisterEnum("protocol.CMsgDOTAJoinChatChannelResponse_Result", CMsgDOTAJoinChatChannelResponse_Result_name, CMsgDOTAJoinChatChannelResponse_Result_value)
	proto.RegisterType((*CMsgClientToGCPrivateChatInvite)(nil), "protocol.CMsgClientToGCPrivateChatInvite")
	proto.RegisterType((*CMsgClientToGCPrivateChatKick)(nil), "protocol.CMsgClientToGCPrivateChatKick")
	proto.RegisterType((*CMsgClientToGCPrivateChatPromote)(nil), "protocol.CMsgClientToGCPrivateChatPromote")
	proto.RegisterType((*CMsgClientToGCPrivateChatDemote)(nil), "protocol.CMsgClientToGCPrivateChatDemote")
	proto.RegisterType((*CMsgGCToClientPrivateChatResponse)(nil), "protocol.CMsgGCToClientPrivateChatResponse")
	proto.RegisterType((*CMsgDOTAJoinChatChannel)(nil), "protocol.CMsgDOTAJoinChatChannel")
	proto.RegisterType((*CMsgDOTALeaveChatChannel)(nil), "protocol.CMsgDOTALeaveChatChannel")
	proto.RegisterType((*CMsgGCChatReportPublicSpam)(nil), "protocol.CMsgGCChatReportPublicSpam")
	proto.RegisterType((*CMsgDOTAChatModeratorBan)(nil), "protocol.CMsgDOTAChatModeratorBan")
	proto.RegisterType((*CMsgDOTAChatMessage)(nil), "protocol.CMsgDOTAChatMessage")
	proto.RegisterType((*CMsgDOTAChatMessage_DiceRoll)(nil), "protocol.CMsgDOTAChatMessage.DiceRoll")
	proto.RegisterType((*CMsgDOTAChatMessage_TriviaAnswered)(nil), "protocol.CMsgDOTAChatMessage.TriviaAnswered")
	proto.RegisterType((*CMsgDOTAChatMessage_PlayerDraftPick)(nil), "protocol.CMsgDOTAChatMessage.PlayerDraftPick")
	proto.RegisterType((*CMsgDOTAChatMember)(nil), "protocol.CMsgDOTAChatMember")
	proto.RegisterType((*CMsgDOTAJoinChatChannelResponse)(nil), "protocol.CMsgDOTAJoinChatChannelResponse")
	proto.RegisterType((*CMsgDOTAOtherJoinedChatChannel)(nil), "protocol.CMsgDOTAOtherJoinedChatChannel")
	proto.RegisterType((*CMsgDOTAOtherLeftChatChannel)(nil), "protocol.CMsgDOTAOtherLeftChatChannel")
	proto.RegisterType((*CMsgDOTARequestChatChannelList)(nil), "protocol.CMsgDOTARequestChatChannelList")
	proto.RegisterType((*CMsgDOTARequestChatChannelListResponse)(nil), "protocol.CMsgDOTARequestChatChannelListResponse")
	proto.RegisterType((*CMsgDOTARequestChatChannelListResponse_ChatChannel)(nil), "protocol.CMsgDOTARequestChatChannelListResponse.ChatChannel")
	proto.RegisterType((*CMsgDOTAChatGetUserListResponse)(nil), "protocol.CMsgDOTAChatGetUserListResponse")
	proto.RegisterType((*CMsgDOTAChatGetUserListResponse_Member)(nil), "protocol.CMsgDOTAChatGetUserListResponse.Member")
	proto.RegisterType((*CMsgDOTAChatGetMemberCount)(nil), "protocol.CMsgDOTAChatGetMemberCount")
	proto.RegisterType((*CMsgDOTAChatGetMemberCountResponse)(nil), "protocol.CMsgDOTAChatGetMemberCountResponse")
	proto.RegisterType((*CMsgDOTAChatRegionsEnabled)(nil), "protocol.CMsgDOTAChatRegionsEnabled")
	proto.RegisterType((*CMsgDOTAChatRegionsEnabled_Region)(nil), "protocol.CMsgDOTAChatRegionsEnabled.Region")
}

func init() {
	proto.RegisterFile("dota_gcmessages_client_chat.proto", fileDescriptor_56aef27c555bd81b)
}

var fileDescriptor_56aef27c555bd81b = []byte{
	// 2530 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0xcb, 0x6f, 0x1c, 0xc7,
	0xd1, 0xf7, 0x2e, 0x5f, 0xcb, 0x5a, 0x3e, 0x86, 0x4d, 0x8a, 0x1c, 0xad, 0x44, 0x71, 0xb5, 0xf6,
	0x27, 0xf3, 0x73, 0x6c, 0xc6, 0x51, 0x1c, 0x07, 0x16, 0x92, 0xc3, 0x70, 0x76, 0x48, 0x8d, 0x35,
	0xfb, 0xd0, 0xec, 0x52, 0xb6, 0x80, 0x00, 0x8d, 0xe6, 0x4c, 0x73, 0x35, 0xe6, 0x3c, 0xd6, 0x33,
	0xb3, 0x14, 0x79, 0x0b, 0x72, 0x08, 0x82, 0xe4, 0x16, 0x20, 0x40, 0x2e, 0xc9, 0x35, 0xc7, 0x5c,
	0x72, 0x0b, 0x72, 0x0c, 0x90, 0x3f, 0x27, 0xc8, 0x3d, 0x48, 0xd0, 0xdd, 0xf3, 0x5c, 0x2e, 0x29,
	0x07, 0x32, 0x82, 0x5c, 0xc8, 0xed, 0xaa, 0x5f, 0x55, 0x57, 0x77, 0x55, 0xd7, 0x63, 0xe0, 0xa1,
	0x1d, 0xc4, 0x04, 0x8f, 0x2c, 0x8f, 0x46, 0x11, 0x19, 0xd1, 0x08, 0x5b, 0xae, 0x43, 0xfd, 0x18,
	0x5b, 0xaf, 0x48, 0x7c, 0x30, 0x0e, 0x83, 0x38, 0x40, 0x35, 0xfe, 0xcf, 0x0a, 0xdc, 0xc6, 0x0e,
	0x07, 0x47, 0xaf, 0x48, 0x48, 0x6d, 0x4c, 0xfd, 0x89, 0x17, 0x09, 0x48, 0xeb, 0x97, 0x15, 0xd8,
	0x53, 0x3b, 0xd1, 0x48, 0xe5, 0xc2, 0xc3, 0xe0, 0x58, 0xed, 0x87, 0xce, 0x05, 0x89, 0xa9, 0xfa,
	0x8a, 0xc4, 0xba, 0x7f, 0xe1, 0xc4, 0x14, 0x7d, 0x06, 0x77, 0xc7, 0x82, 0xc8, 0x95, 0xb3, 0x3f,
	0xbe, 0x4f, 0x5d, 0xec, 0x13, 0x8f, 0xca, 0x95, 0x66, 0x65, 0x7f, 0xd9, 0xdc, 0x1e, 0xe7, 0x52,
	0xaa, 0x60, 0x77, 0x89, 0x47, 0xd1, 0x87, 0x80, 0x1c, 0xae, 0xc4, 0xc6, 0xc4, 0xb2, 0x82, 0x89,
	0x1f, 0x63, 0xc7, 0x96, 0xab, 0xcd, 0xca, 0xfe, 0xaa, 0x29, 0x25, 0x1c, 0x45, 0x30, 0x74, 0xbb,
	0xf5, 0xb3, 0x0a, 0xec, 0xde, 0x68, 0xcc, 0x33, 0xc7, 0x3a, 0x7f, 0x1b, 0x53, 0x1e, 0xc1, 0xfa,
	0xb9, 0x63, 0x9d, 0x5f, 0xb7, 0x63, 0x95, 0x91, 0x73, 0x23, 0x7e, 0x55, 0x81, 0xe6, 0x8d, 0x46,
	0xf4, 0xc3, 0xc0, 0x0b, 0xde, 0xfa, 0x4a, 0xc6, 0x42, 0xcb, 0x8c, 0x2b, 0x49, 0x38, 0xb9, 0x35,
	0xbf, 0xb8, 0xcd, 0x3f, 0x6d, 0xfa, 0xb6, 0xc6, 0x7c, 0x00, 0x1b, 0x36, 0x9d, 0x6d, 0xcb, 0xba,
	0x60, 0xe4, 0xa6, 0xfc, 0x7d, 0x1e, 0x1e, 0x32, 0x53, 0x8e, 0xd5, 0x61, 0x20, 0xcc, 0x29, 0x98,
	0x62, 0xd2, 0x68, 0x1c, 0xf8, 0xd1, 0x5b, 0x19, 0x33, 0x80, 0xc5, 0x90, 0x46, 0x13, 0x37, 0xe6,
	0x16, 0xac, 0x3d, 0x7e, 0x7c, 0x90, 0xc6, 0xef, 0xc1, 0x1b, 0xf7, 0x3d, 0x30, 0xb9, 0xe4, 0x93,
	0xa5, 0xc1, 0x89, 0xaa, 0x6a, 0x83, 0x81, 0x99, 0xa8, 0x42, 0x0d, 0xa8, 0x4d, 0x22, 0x1a, 0xf2,
	0xed, 0xe7, 0xf8, 0xf6, 0xd9, 0xba, 0xf5, 0xfb, 0x39, 0x58, 0x14, 0x72, 0xa8, 0x0e, 0xa9, 0xa4,
	0xf4, 0x0e, 0xba, 0x0b, 0x77, 0x8e, 0x14, 0xdd, 0x38, 0x31, 0x35, 0xac, 0x9a, 0x9a, 0x32, 0xd4,
	0x7b, 0x5d, 0x6c, 0xf4, 0xd4, 0x67, 0x52, 0x05, 0xdd, 0x83, 0x9d, 0x94, 0x35, 0x78, 0x6e, 0xe0,
	0xa1, 0xa9, 0x74, 0x07, 0x8a, 0xca, 0x10, 0x52, 0x15, 0x6d, 0x81, 0x94, 0x31, 0xdb, 0x3d, 0x6c,
	0xf4, 0x94, 0xb6, 0x34, 0x57, 0xd4, 0xd6, 0xed, 0xe1, 0xbe, 0x66, 0x76, 0xf4, 0xc1, 0x80, 0x09,
	0xcc, 0xa3, 0x06, 0x6c, 0xa7, 0x2c, 0xc5, 0x30, 0x35, 0xa5, 0xfd, 0x12, 0x77, 0xb4, 0xce, 0xa1,
	0x66, 0x4a, 0x0b, 0x48, 0x86, 0xad, 0x5c, 0x6c, 0x88, 0x95, 0x94, 0xb3, 0x84, 0xf6, 0xe0, 0x5e,
	0x41, 0xa1, 0xa9, 0x75, 0x14, 0xbd, 0xab, 0x77, 0x8f, 0xb1, 0xd2, 0xee, 0xe8, 0xdd, 0x81, 0x54,
	0x43, 0x9b, 0xb0, 0x5e, 0x04, 0xf4, 0x7a, 0x1d, 0x69, 0x19, 0x3d, 0x84, 0xdd, 0x6b, 0x87, 0x32,
	0x95, 0xa1, 0x86, 0x0d, 0xbd, 0xa3, 0x0f, 0xb5, 0xb6, 0x04, 0xa8, 0x09, 0xf7, 0x53, 0xc8, 0x49,
	0xf7, 0x59, 0xb7, 0xf7, 0x45, 0x17, 0xab, 0x4f, 0x95, 0x6e, 0x57, 0x33, 0x70, 0x57, 0xe9, 0x68,
	0x52, 0xbd, 0x68, 0x54, 0x8a, 0x38, 0x19, 0x68, 0xa6, 0xb4, 0x52, 0x3c, 0x65, 0xca, 0xd1, 0x4c,
	0xb3, 0x67, 0x4a, 0xab, 0x68, 0x17, 0xee, 0x66, 0x3b, 0x2b, 0x5d, 0x76, 0x98, 0x67, 0xba, 0xfa,
	0x4c, 0x98, 0x2b, 0xad, 0x15, 0x25, 0xd3, 0x4b, 0x10, 0xac, 0xf5, 0xd6, 0x5f, 0x2b, 0xb0, 0xc3,
	0x5c, 0xdf, 0xee, 0x0d, 0x95, 0xcf, 0x03, 0xc7, 0x2f, 0x44, 0x0c, 0x7a, 0x08, 0x2b, 0xa5, 0xd8,
	0xaa, 0x72, 0xe7, 0xd6, 0xad, 0x42, 0x40, 0xfd, 0x24, 0x87, 0xc4, 0x57, 0x63, 0x2a, 0xcf, 0xf3,
	0xb0, 0xda, 0xcb, 0xc3, 0x8a, 0xe9, 0x2d, 0xe8, 0x1c, 0x5e, 0x8d, 0x29, 0x8e, 0x9f, 0xc8, 0x09,
	0x39, 0x23, 0x99, 0x74, 0xe4, 0x04, 0x3e, 0x71, 0x33, 0xed, 0x8c, 0x8a, 0xfe, 0x1f, 0xa4, 0xc8,
	0x71, 0x59, 0xca, 0x0d, 0xe9, 0x57, 0xd4, 0x8a, 0x9d, 0xc0, 0x97, 0x17, 0x9a, 0x95, 0xfd, 0x9a,
	0xb9, 0x2e, 0xe8, 0x66, 0x4a, 0x6e, 0x7d, 0x06, 0x72, 0x7a, 0x0c, 0x83, 0x92, 0x8b, 0x62, 0xe4,
	0xa3, 0x5d, 0x80, 0xd4, 0x48, 0xc7, 0xe6, 0x2f, 0x64, 0xde, 0x5c, 0x4e, 0x28, 0xba, 0xdd, 0xb2,
	0xa0, 0x21, 0x82, 0x5f, 0x44, 0xfb, 0x38, 0x08, 0xe3, 0xfe, 0xe4, 0xd4, 0x75, 0xac, 0xc1, 0x98,
	0x78, 0x6f, 0x10, 0x66, 0x39, 0x2f, 0x65, 0xb3, 0xa0, 0x2f, 0xe4, 0xbc, 0x84, 0x7c, 0x12, 0xd1,
	0x50, 0xb7, 0x5b, 0x71, 0x6e, 0x1f, 0xdb, 0xa6, 0x13, 0xd8, 0x34, 0x24, 0x71, 0x10, 0x1e, 0x12,
	0xff, 0x4d, 0x5b, 0xec, 0x02, 0x5c, 0x4b, 0x1d, 0xcb, 0x24, 0x4d, 0x1a, 0xec, 0xf9, 0xd9, 0x93,
	0x90, 0xf0, 0xcb, 0x99, 0xe3, 0xcc, 0x6c, 0xdd, 0xfa, 0xc3, 0x06, 0x6c, 0x96, 0xb6, 0x15, 0x95,
	0x6c, 0x4a, 0x65, 0x65, 0x5a, 0x65, 0xd9, 0xa0, 0xea, 0xb4, 0x41, 0x0f, 0x61, 0x65, 0x4c, 0xc3,
	0x28, 0xf0, 0x09, 0x2e, 0x3c, 0xfa, 0x7a, 0x42, 0xe3, 0x71, 0x81, 0x60, 0x3e, 0xa6, 0x97, 0x31,
	0x8f, 0x87, 0x65, 0x93, 0xff, 0x46, 0xf7, 0x61, 0x39, 0x76, 0x3c, 0x1a, 0xc5, 0xc4, 0x1b, 0x73,
	0x37, 0xae, 0x9a, 0x39, 0x81, 0x65, 0xb5, 0x68, 0x32, 0x1a, 0xd1, 0x28, 0xc6, 0xa2, 0x6a, 0x15,
	0xf3, 0xe5, 0x22, 0x47, 0x6f, 0x27, 0x00, 0x51, 0x34, 0xb3, 0xb4, 0x89, 0x0e, 0x60, 0x73, 0x4a,
	0x94, 0x9b, 0xb5, 0xc4, 0xf7, 0xde, 0x28, 0x09, 0x71, 0xe3, 0x0e, 0xe1, 0xc1, 0x19, 0xf1, 0x63,
	0x12, 0x5d, 0x61, 0x3b, 0x24, 0x67, 0x31, 0x0e, 0x5e, 0xfb, 0x34, 0x2c, 0xee, 0x57, 0xe3, 0xfb,
	0x35, 0x12, 0x54, 0x9b, 0x81, 0x7a, 0x0c, 0x93, 0xef, 0xd9, 0x86, 0xbd, 0xb2, 0x8e, 0xb1, 0x4b,
	0xae, 0xca, 0x4a, 0x96, 0xb9, 0x92, 0x7b, 0x45, 0x25, 0x7d, 0x0e, 0xca, 0xb5, 0xdc, 0x85, 0x1a,
	0xbd, 0xa0, 0x02, 0x0e, 0x1c, 0xbe, 0xc4, 0xd7, 0xba, 0x8d, 0x7e, 0x00, 0x3b, 0x53, 0x87, 0x8a,
	0x03, 0xec, 0x06, 0xa7, 0xa7, 0x57, 0x72, 0x9d, 0x3f, 0x81, 0xad, 0xd2, 0xc1, 0x86, 0x81, 0xc1,
	0x78, 0xcc, 0x37, 0x42, 0xe3, 0x38, 0x70, 0xfc, 0x38, 0x92, 0x57, 0xb8, 0xd6, 0x3a, 0xa7, 0xf5,
	0x39, 0x09, 0xdd, 0x83, 0x65, 0x2b, 0x70, 0x7c, 0x7c, 0xe6, 0x3a, 0x63, 0x79, 0x95, 0xeb, 0xaa,
	0x31, 0xc2, 0x91, 0xeb, 0x8c, 0xd1, 0x1e, 0x2c, 0x27, 0x27, 0x71, 0x6c, 0x79, 0xad, 0x59, 0xd9,
	0x5f, 0x78, 0x52, 0xfd, 0xe8, 0x7b, 0x66, 0x4d, 0x10, 0x75, 0x1b, 0xfd, 0x10, 0x64, 0xde, 0xe4,
	0xe0, 0x71, 0x18, 0x9c, 0x39, 0x6e, 0xc9, 0x4d, 0xeb, 0x7c, 0xb3, 0x3b, 0x9c, 0xdf, 0x17, 0xec,
	0xfc, 0xac, 0x33, 0x5e, 0x8a, 0x34, 0xe3, 0xa5, 0x20, 0x15, 0x96, 0x6d, 0xc7, 0xa2, 0x38, 0x0c,
	0x5c, 0x57, 0xde, 0x68, 0x56, 0xf6, 0xeb, 0x8f, 0x1f, 0x95, 0xcb, 0xd4, 0x54, 0x34, 0x1f, 0xb4,
	0x1d, 0x8b, 0x9a, 0x81, 0xeb, 0x9a, 0x35, 0x3b, 0xf9, 0x85, 0xde, 0x83, 0xb5, 0xc4, 0x4a, 0x12,
	0xc6, 0x57, 0x6c, 0x2f, 0xc4, 0xa3, 0x78, 0x45, 0xd8, 0xc6, 0x88, 0xba, 0x9d, 0xa3, 0xf8, 0xbd,
	0x32, 0xd4, 0x66, 0x01, 0xc5, 0x2f, 0x54, 0xb7, 0xd1, 0x13, 0x68, 0x14, 0x51, 0xd6, 0x24, 0x8a,
	0x03, 0x0f, 0x8f, 0x88, 0x47, 0x99, 0xc4, 0x16, 0x97, 0xd8, 0xce, 0x25, 0x54, 0xce, 0x3f, 0x26,
	0x1e, 0x4d, 0x42, 0xb3, 0x20, 0x3b, 0x26, 0x51, 0x74, 0x4e, 0xaf, 0xe4, 0x3b, 0x49, 0x68, 0x66,
	0x42, 0x7d, 0xc1, 0x60, 0x5e, 0x9f, 0x59, 0xdb, 0x1d, 0x5b, 0xde, 0xe6, 0x97, 0xb5, 0x75, 0xbd,
	0xb2, 0xeb, 0x36, 0xda, 0x86, 0xc5, 0x28, 0x26, 0xf1, 0x24, 0x92, 0x77, 0x38, 0x2a, 0x59, 0xb1,
	0x47, 0xe5, 0xd2, 0x11, 0xb1, 0xae, 0xf0, 0x29, 0x89, 0x63, 0x97, 0x62, 0x6b, 0x32, 0xc6, 0x17,
	0x8e, 0x15, 0x07, 0xe1, 0x95, 0x2c, 0x73, 0xd7, 0x6f, 0x0b, 0xc0, 0x21, 0xe7, 0xab, 0x93, 0xf1,
	0x0b, 0xc1, 0x65, 0x7d, 0x4b, 0x41, 0x26, 0x8a, 0x43, 0x4a, 0xce, 0xe5, 0x5d, 0xd1, 0xb7, 0x9c,
	0xa6, 0xe0, 0x01, 0x27, 0xa3, 0x3d, 0xa8, 0x9f, 0x12, 0x7b, 0x44, 0xb1, 0x4b, 0x2f, 0xa8, 0x2b,
	0xdf, 0xe5, 0x28, 0xe0, 0x24, 0x83, 0x51, 0xd0, 0x77, 0x21, 0x8d, 0x56, 0x3c, 0x66, 0x1d, 0xe2,
	0x2b, 0x1a, 0x06, 0xec, 0x4c, 0x0d, 0x8e, 0x4c, 0x9f, 0x68, 0xdf, 0xb1, 0xce, 0x9f, 0xd2, 0x30,
	0xd0, 0x6d, 0xf4, 0x7d, 0xd8, 0xbe, 0x2e, 0x10, 0x06, 0x2e, 0x95, 0xef, 0xf1, 0xab, 0xdb, 0x9c,
	0x12, 0x31, 0x03, 0x97, 0xa2, 0x8f, 0xf2, 0x3c, 0x70, 0x4a, 0xfc, 0x6c, 0x93, 0x07, 0xa2, 0xf1,
	0x4b, 0x58, 0x87, 0xc4, 0x4f, 0xf6, 0x78, 0x0e, 0xab, 0x71, 0xe8, 0x5c, 0x38, 0x04, 0x13, 0x3f,
	0x7a, 0x4d, 0x43, 0xb9, 0xc9, 0x83, 0xed, 0xc3, 0xdb, 0x83, 0x6d, 0xc8, 0x45, 0x14, 0x2e, 0x41,
	0x6d, 0x73, 0x25, 0x2e, 0xac, 0xd1, 0x27, 0xb0, 0x15, 0xd2, 0xaf, 0x27, 0x34, 0xe2, 0xed, 0xf8,
	0xa9, 0xe3, 0x3a, 0x22, 0xf8, 0x1e, 0x66, 0x0f, 0x09, 0x65, 0x7c, 0x45, 0xb0, 0xb3, 0x74, 0x1b,
	0xe3, 0x33, 0x97, 0x8c, 0x22, 0xb9, 0x25, 0x32, 0x23, 0xa3, 0x1c, 0x31, 0x02, 0x7a, 0x0c, 0x77,
	0xa2, 0x98, 0x84, 0x4c, 0xe5, 0x99, 0xe3, 0xdb, 0x8e, 0x3f, 0xc2, 0x1e, 0x89, 0xad, 0x57, 0xf2,
	0xbb, 0xdc, 0x81, 0x9b, 0x09, 0xf3, 0x48, 0xf0, 0x3a, 0x8c, 0x85, 0x9a, 0xb0, 0x62, 0xc5, 0xa1,
	0x8b, 0x9d, 0x08, 0xdb, 0xc1, 0x6b, 0x5f, 0x7e, 0x8f, 0x43, 0x81, 0xd1, 0xf4, 0xa8, 0x1d, 0xbc,
	0xf6, 0xd1, 0x3e, 0x48, 0x67, 0xe4, 0x22, 0x08, 0x79, 0x66, 0xa1, 0xc4, 0x63, 0x66, 0xfe, 0x1f,
	0xdf, 0x7a, 0x2d, 0xa5, 0x0f, 0x29, 0xf1, 0x74, 0x9b, 0xed, 0x5f, 0x46, 0x7e, 0x3d, 0x21, 0xcc,
	0x72, 0xf9, 0x11, 0x87, 0x6f, 0x16, 0xe1, 0xcf, 0x05, 0x0b, 0xfd, 0x38, 0xcf, 0xe6, 0x49, 0x3a,
	0x49, 0xb2, 0xa4, 0x63, 0x9d, 0xcb, 0xef, 0x67, 0xb7, 0x91, 0x3a, 0x59, 0xe4, 0x45, 0x91, 0x22,
	0xd9, 0x10, 0xf2, 0x12, 0x36, 0xae, 0x8b, 0xed, 0x73, 0xf7, 0x7c, 0x74, 0xbb, 0x7b, 0xa6, 0x34,
	0x99, 0xeb, 0xe3, 0x32, 0xa1, 0xf1, 0x25, 0xd4, 0xd2, 0x7c, 0xc1, 0xd2, 0x2f, 0xcb, 0x32, 0xd8,
	0x73, 0x7c, 0x5e, 0x04, 0x17, 0xcc, 0x25, 0xb6, 0xee, 0x38, 0x7e, 0xce, 0x22, 0x97, 0xbc, 0x00,
	0xa6, 0x2c, 0x72, 0xc9, 0x1e, 0x5b, 0xd2, 0x44, 0xcf, 0x71, 0x46, 0xb2, 0x6a, 0xfc, 0xa3, 0x02,
	0x6b, 0xe5, 0xe8, 0x60, 0x0f, 0x83, 0x7b, 0xdb, 0x09, 0xfc, 0xbc, 0xd0, 0x42, 0x4a, 0x12, 0xa5,
	0x54, 0x04, 0x1f, 0x76, 0x7c, 0x9b, 0x5e, 0x26, 0xd5, 0xbd, 0x2e, 0x68, 0x3a, 0x23, 0xa1, 0x4f,
	0x61, 0x47, 0x24, 0xb1, 0x54, 0x2c, 0xc2, 0x56, 0x10, 0x86, 0xd4, 0x8a, 0x93, 0x72, 0x7f, 0x87,
	0xb3, 0x9f, 0xa7, 0x5c, 0x55, 0x30, 0xd1, 0x27, 0xb0, 0x3d, 0x2d, 0x77, 0xe1, 0xd0, 0xd7, 0xd4,
	0xe6, 0x45, 0x99, 0x65, 0x92, 0x92, 0xd8, 0x0b, 0xce, 0x63, 0x09, 0x4b, 0x48, 0x25, 0x4f, 0x23,
	0x29, 0x23, 0xa2, 0x5c, 0x6f, 0x70, 0x96, 0x38, 0xa3, 0x28, 0x26, 0x8d, 0x23, 0x58, 0x9f, 0x76,
	0x5e, 0xa9, 0x84, 0x54, 0x66, 0x94, 0x10, 0xde, 0x1c, 0x10, 0x2f, 0xb9, 0x57, 0xfe, 0xbb, 0xf5,
	0xeb, 0x0a, 0xa0, 0xb2, 0x3f, 0xbd, 0x53, 0x1a, 0x32, 0x37, 0x44, 0x69, 0x74, 0x32, 0x55, 0x8b,
	0xe6, 0x12, 0x5f, 0xcf, 0xe8, 0x42, 0xaa, 0xd7, 0xbb, 0x90, 0x19, 0x25, 0x67, 0x6e, 0x56, 0xc9,
	0xc9, 0xd3, 0xe7, 0x7c, 0x31, 0x7d, 0xb6, 0xfe, 0x59, 0x13, 0xa3, 0xe1, 0x8c, 0xe6, 0x38, 0x9b,
	0xc6, 0x1a, 0x50, 0x0b, 0x93, 0xdf, 0x89, 0x7f, 0xb3, 0xf5, 0x37, 0x69, 0xa0, 0xcb, 0xad, 0xd6,
	0x1c, 0x3f, 0x62, 0xa1, 0xd5, 0xda, 0x83, 0xba, 0x47, 0x2e, 0xb1, 0xc7, 0x6f, 0x23, 0x35, 0x0f,
	0x3c, 0x72, 0x29, 0xee, 0x27, 0x42, 0x9f, 0xc2, 0x52, 0xca, 0x5c, 0x68, 0xce, 0xed, 0xd7, 0x1f,
	0xdf, 0xbf, 0xe9, 0x7d, 0x30, 0x90, 0x99, 0x82, 0xaf, 0x35, 0xee, 0x8b, 0xdf, 0x6a, 0xe3, 0xfe,
	0x22, 0x7b, 0x22, 0x4b, 0x5c, 0xef, 0xc7, 0xd7, 0x8d, 0xba, 0xe1, 0x3e, 0xd3, 0x29, 0x73, 0xe5,
	0xf3, 0x9e, 0xde, 0xc5, 0xd3, 0xa3, 0xe6, 0x07, 0xb0, 0x31, 0xb2, 0xb0, 0xe3, 0x3b, 0xb1, 0x43,
	0x58, 0x3e, 0xfc, 0x2a, 0x70, 0x7c, 0xde, 0xac, 0xd5, 0xcc, 0xf5, 0x91, 0xa5, 0xa7, 0x74, 0xa6,
	0x7b, 0x96, 0xf3, 0x97, 0x67, 0x39, 0xff, 0x7d, 0x58, 0x7f, 0x4d, 0x5d, 0x2b, 0xf0, 0x28, 0x4e,
	0x3e, 0xf4, 0xf0, 0x56, 0x6c, 0xd9, 0x5c, 0x4b, 0xc8, 0x69, 0xd3, 0xec, 0x03, 0x8a, 0xc6, 0xd4,
	0x72, 0x88, 0x8b, 0x59, 0x11, 0x76, 0x5c, 0x3a, 0xa2, 0x11, 0x6f, 0xc6, 0xd6, 0x1e, 0x37, 0xf3,
	0x03, 0x6a, 0xec, 0x54, 0x03, 0x01, 0xec, 0x67, 0xb8, 0x27, 0xbb, 0xe7, 0x78, 0x36, 0x07, 0x77,
	0x03, 0x9f, 0x9a, 0x1b, 0xd1, 0x34, 0xbd, 0xf5, 0xaf, 0x7c, 0x76, 0x96, 0xa0, 0x74, 0x1f, 0xd2,
	0x3b, 0x6c, 0x4c, 0xd4, 0xbb, 0x2f, 0x14, 0x43, 0x6f, 0x67, 0x03, 0xe4, 0xf0, 0x65, 0x5f, 0x93,
	0x2a, 0xe8, 0x0e, 0x6c, 0x28, 0xaa, 0xda, 0x3b, 0xe9, 0x0e, 0xf9, 0x54, 0x7b, 0xd4, 0x3b, 0xe9,
	0xb6, 0xa5, 0x2a, 0x5a, 0x03, 0x50, 0xd4, 0xa7, 0x98, 0xcd, 0x81, 0x1a, 0x9b, 0x99, 0x77, 0xe1,
	0x2e, 0x9b, 0x2b, 0xb1, 0xde, 0xc5, 0xc3, 0x5e, 0x0f, 0x77, 0x94, 0xee, 0xcb, 0x54, 0xd3, 0x40,
	0x9a, 0x47, 0x3b, 0xb0, 0x99, 0x8f, 0xae, 0x58, 0xfb, 0x52, 0xd5, 0xb4, 0xb6, 0xd6, 0x96, 0x16,
	0x98, 0x29, 0xe9, 0x86, 0x47, 0x27, 0x86, 0x21, 0x2d, 0xb2, 0x81, 0xbd, 0x48, 0xc1, 0xbd, 0x17,
	0x9a, 0x79, 0x64, 0xf4, 0xbe, 0xd0, 0xda, 0xd2, 0x12, 0xda, 0x06, 0x24, 0xb6, 0xc4, 0xc3, 0x1e,
	0x56, 0xda, 0x6d, 0x31, 0xcc, 0xd6, 0xd8, 0x48, 0x5a, 0xb4, 0x1b, 0xb7, 0xf5, 0x81, 0x72, 0xc8,
	0x2c, 0x5b, 0x46, 0x0f, 0xa0, 0xd1, 0x37, 0xf5, 0x17, 0x6c, 0x77, 0xf5, 0xa9, 0x32, 0x14, 0xb3,
	0xb4, 0x96, 0x5a, 0x0e, 0xd7, 0xf8, 0xe5, 0x91, 0xbf, 0x8e, 0xde, 0x85, 0xbd, 0x59, 0xf2, 0x46,
	0x4f, 0x7d, 0x96, 0x2a, 0x59, 0x61, 0xe7, 0x2b, 0x81, 0xd8, 0xbc, 0xac, 0xb5, 0xa5, 0x55, 0xb4,
	0x05, 0x12, 0xbf, 0x17, 0xfe, 0x45, 0xc0, 0x10, 0xc7, 0x58, 0x43, 0xef, 0x41, 0x53, 0xeb, 0x0e,
	0xf8, 0x67, 0x87, 0xbe, 0xa6, 0xea, 0x8a, 0x81, 0x99, 0xb4, 0x6e, 0x68, 0xc7, 0xda, 0x20, 0x55,
	0xba, 0xce, 0xa6, 0xfb, 0xae, 0xf6, 0x05, 0xee, 0x1b, 0xca, 0x4b, 0xcd, 0xc4, 0x99, 0x1a, 0xcd,
	0xd0, 0x8f, 0xf5, 0x43, 0x43, 0x93, 0x24, 0x76, 0x7b, 0x03, 0xdd, 0xd0, 0xba, 0xc3, 0x64, 0x74,
	0xdf, 0x40, 0x0d, 0xd8, 0x9e, 0x96, 0x39, 0x64, 0xf7, 0xd2, 0x96, 0x50, 0xeb, 0x2f, 0x15, 0x78,
	0x90, 0xbe, 0x97, 0x5e, 0xfc, 0x8a, 0x86, 0x2c, 0xb0, 0xa9, 0x7d, 0xfb, 0x6c, 0xbb, 0x78, 0xdb,
	0xa8, 0x36, 0x23, 0x49, 0x16, 0x53, 0xec, 0x5c, 0x39, 0xc5, 0xce, 0x78, 0x42, 0xf3, 0xb7, 0xe7,
	0xcf, 0x85, 0x52, 0xfe, 0xfc, 0x69, 0x05, 0xee, 0x97, 0xec, 0x37, 0xe8, 0x59, 0xfc, 0x1f, 0x58,
	0x5f, 0x34, 0xad, 0xfa, 0x46, 0xd3, 0x66, 0xa5, 0xf6, 0x56, 0x33, 0xbf, 0x41, 0x53, 0x74, 0x5e,
	0x85, 0xfd, 0x0d, 0x27, 0x8a, 0x5b, 0x7f, 0xaa, 0xc2, 0xa3, 0xdb, 0x21, 0x59, 0xae, 0xff, 0x12,
	0x6a, 0x89, 0xf6, 0x48, 0xae, 0xf0, 0x6c, 0xfb, 0xa3, 0xeb, 0x89, 0xed, 0x76, 0x1d, 0x07, 0xc5,
	0x9c, 0x97, 0x69, 0x6b, 0xfc, 0xb1, 0x02, 0xf5, 0xdb, 0x3e, 0xbd, 0x54, 0xae, 0x57, 0x8e, 0x3d,
	0xa8, 0xfb, 0x13, 0x2f, 0x2b, 0x0d, 0xa2, 0x73, 0x00, 0x7f, 0xe2, 0x75, 0x6e, 0x48, 0xf1, 0x73,
	0xdf, 0x66, 0x8a, 0x6f, 0xfd, 0xa6, 0x9a, 0xd7, 0x46, 0xa6, 0xe4, 0x98, 0xc6, 0xec, 0xca, 0x4b,
	0xf7, 0xf5, 0x06, 0xf7, 0x7e, 0x9e, 0xd7, 0xae, 0x2a, 0xbf, 0xcd, 0x8f, 0x67, 0xd7, 0xae, 0x19,
	0xaa, 0x0f, 0xa6, 0xea, 0x59, 0xe3, 0xe7, 0x15, 0x58, 0xfc, 0x9f, 0xe8, 0x19, 0x7e, 0x57, 0x11,
	0x9f, 0x93, 0x0a, 0xc6, 0x0b, 0xbb, 0x54, 0x36, 0x07, 0x7f, 0x13, 0xc7, 0x4e, 0xfb, 0xad, 0xfa,
	0xad, 0xfa, 0xed, 0x6f, 0x15, 0x68, 0xdd, 0x6c, 0x9f, 0x79, 0x53, 0xeb, 0xf2, 0xdf, 0xb6, 0x93,
	0x19, 0x20, 0x7c, 0x8b, 0xf9, 0x07, 0x84, 0xc4, 0x09, 0x75, 0x2f, 0xb7, 0xb5, 0xf5, 0xe7, 0x6a,
	0xf9, 0xaa, 0x85, 0xa2, 0x48, 0xf3, 0xc9, 0xa9, 0x4b, 0x6d, 0xf4, 0x21, 0x20, 0xca, 0x7f, 0x62,
	0xe2, 0xba, 0x38, 0x14, 0x4c, 0x7e, 0x90, 0x9a, 0x29, 0x09, 0x8e, 0xe2, 0xba, 0x89, 0x10, 0x1a,
	0xc2, 0xba, 0xa0, 0xd9, 0x19, 0x54, 0x04, 0xe5, 0x77, 0x66, 0x07, 0x65, 0x79, 0xb3, 0x03, 0xb1,
	0x34, 0xd7, 0x12, 0x1d, 0x09, 0xb7, 0xf1, 0xdb, 0x0a, 0xab, 0xe1, 0xec, 0x37, 0x3f, 0x90, 0xe3,
	0x63, 0x97, 0xc4, 0x4e, 0x3c, 0xb1, 0xc5, 0x8d, 0x56, 0xcd, 0xba, 0xe7, 0xf8, 0x46, 0x42, 0xe2,
	0x10, 0x72, 0x99, 0x43, 0xaa, 0x09, 0x84, 0x5c, 0x66, 0x90, 0x77, 0x61, 0x95, 0x6b, 0x09, 0xfc,
	0x91, 0xc0, 0xcc, 0x71, 0x0c, 0x53, 0x6d, 0xa4, 0x34, 0x0e, 0x62, 0x7a, 0x32, 0xd0, 0x7c, 0x02,
	0x22, 0x97, 0x19, 0xe8, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x19, 0x26, 0xa6, 0xde, 0x1a,
	0x00, 0x00,
}
